#!/usr/bin/env bash
# Regenerate docs/cli-reference.md straight from the live Typer CLI, so the command
# reference can never drift from the code. The CI component gate runs this and fails if
# the committed copy is stale.
#
# Locally:  make docs   (or)   bash scripts/gen-docs.sh
# Requires: pip install -e ".[cli,docs]"
#
# Internal engineering notebooks are regenerated separately with the helpers under
# scripts/internal/ because their committed forms carry executed GPU renders.
set -euo pipefail

cd "$(dirname "$0")/.."
if [ -n "${PYTHON:-}" ]; then
  PY="$PYTHON"
elif [ -x ".venv/bin/python" ]; then
  PY=".venv/bin/python"
else
  PY="python3"
fi
OUT="docs/cli-reference.md"

"$PY" -m typer usd_cli.main utils docs --name usd-cli --output "$OUT"

# Prepend a "do not edit" banner so nobody hand-edits the generated file.
BANNER='<!-- Generated by scripts/gen-docs.sh from the live usd-cli CLI — do not edit by hand.
     Run `make docs` after changing any command name, help, argument, or option. -->'
printf '%s\n\n%s\n' "$BANNER" "$(cat "$OUT")" > "$OUT"

echo "✓ wrote $OUT"
