# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Agentic geometry workflow contracts."""

from .audit import (
    GEOMETRY_ASSET_AUDIT_SCHEMA_VERSION,
    AuthoringContract,
    GeometryAssetAuditReport,
    GeometryAuditSignal,
    audit_geometry_asset,
    write_audit_artifacts,
)
from .authoring_provider import (
    GEOMETRY_SOURCE_SCHEMA_VERSION,
    ArtifactJsonGeometryAuthoringProvider,
    GeometryAuthoringCapabilityReport,
    GeometryAuthoringExportRequest,
    GeometryAuthoringFailure,
    GeometryAuthoringProvider,
    GeometryAuthoringProviderError,
    GeometryAuthoringProviderIdentity,
    GeometryAuthoringProviderReceipt,
    GeometryAuthoringReference,
    GeometryAuthoringRequest,
    GeometryAuthoringRevisionRequest,
    GeometryCoordinateSystem,
    GeometryPartBinding,
    GeometryRepresentationBinding,
    GeometryRightsAssertion,
    GeometrySemanticParameter,
    GeometrySourceBundle,
    GeometrySourceProvenance,
    HttpJsonGeometryAuthoringProvider,
    geometry_authoring_request_digest,
)
from .policy import (
    GeometryRoute,
    GeometryRouteDecision,
    GeometrySourceCategory,
    route_geometry_request,
)
from .rendering import (
    GEOMETRY_REMOTE_OVRTX_IDENTITY_SCHEMA_VERSION,
    GEOMETRY_RENDER_EVIDENCE_SCHEMA_VERSION,
    GeometryRemoteOvrtxHealth,
    GeometryRemoteOvrtxIdentityEvidence,
    GeometryRenderEvidence,
    GeometryRenderImageBinding,
    GeometryRenderPreset,
    render_geometry_evidence,
)
from .segmentation import (
    SEGMENTATION_HANDOFF_SCHEMA_VERSION,
    GeometrySegmentationHandoff,
    GeometrySegmentationPart,
    SegmentationOutcome,
    consume_segmentation_handoff,
)
from .segmentation_routing import (
    SEGMENTATION_ROUTING_SCHEMA_VERSION,
    GeometrySegmentationRoutingDecision,
    GeometrySegmentationRoutingMetrics,
    SegmentationRoute,
    route_segmentation,
)
from .source_prep import (
    PreparedGeometrySource,
    SourceAuthoringMode,
    SourceFidelityTier,
    prepare_geometry_source,
)
from .workflow import (
    GEOMETRY_HANDOFF_MANIFEST_SCHEMA_VERSION,
    GeometryHandoffReady,
    GeometryOptimizationPolicy,
    GeometryRepairMode,
    GeometrySimReadyMode,
    GeometryWorkflowInput,
    GeometryWorkflowResult,
    run_geometry_workflow,
)

__all__ = [
    "GEOMETRY_ASSET_AUDIT_SCHEMA_VERSION",
    "GEOMETRY_RENDER_EVIDENCE_SCHEMA_VERSION",
    "GEOMETRY_HANDOFF_MANIFEST_SCHEMA_VERSION",
    "GEOMETRY_SOURCE_SCHEMA_VERSION",
    "SEGMENTATION_HANDOFF_SCHEMA_VERSION",
    "SEGMENTATION_ROUTING_SCHEMA_VERSION",
    "GEOMETRY_REMOTE_OVRTX_IDENTITY_SCHEMA_VERSION",
    "GeometryAssetAuditReport",
    "GeometryAuditSignal",
    "GeometryOptimizationPolicy",
    "GeometryHandoffReady",
    "GeometryRemoteOvrtxHealth",
    "GeometryRemoteOvrtxIdentityEvidence",
    "GeometryRepairMode",
    "GeometryRenderEvidence",
    "GeometryRenderImageBinding",
    "GeometryRenderPreset",
    "GeometryRoute",
    "GeometryRouteDecision",
    "GeometrySimReadyMode",
    "GeometrySourceCategory",
    "GeometryWorkflowInput",
    "GeometryWorkflowResult",
    "GeometrySegmentationHandoff",
    "GeometrySegmentationPart",
    "GeometrySegmentationRoutingDecision",
    "GeometrySegmentationRoutingMetrics",
    "PreparedGeometrySource",
    "SegmentationOutcome",
    "SegmentationRoute",
    "AuthoringContract",
    "ArtifactJsonGeometryAuthoringProvider",
    "GeometryAuthoringCapabilityReport",
    "GeometryAuthoringExportRequest",
    "GeometryAuthoringFailure",
    "GeometryAuthoringProvider",
    "GeometryAuthoringProviderError",
    "GeometryAuthoringProviderIdentity",
    "GeometryAuthoringProviderReceipt",
    "GeometryAuthoringReference",
    "GeometryAuthoringRequest",
    "GeometryAuthoringRevisionRequest",
    "GeometryCoordinateSystem",
    "GeometryPartBinding",
    "GeometryRepresentationBinding",
    "GeometryRightsAssertion",
    "GeometrySemanticParameter",
    "GeometrySourceBundle",
    "GeometrySourceProvenance",
    "HttpJsonGeometryAuthoringProvider",
    "SourceAuthoringMode",
    "SourceFidelityTier",
    "audit_geometry_asset",
    "consume_segmentation_handoff",
    "prepare_geometry_source",
    "render_geometry_evidence",
    "route_geometry_request",
    "route_segmentation",
    "run_geometry_workflow",
    "write_audit_artifacts",
    "geometry_authoring_request_digest",
]
