# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Compatibility imports for the standalone authoring-contract package.

New integrations should import from :mod:`geometry_authoring_contracts`.
"""

from geometry_authoring_contracts import (
    GEOMETRY_AUTHORING_CAPABILITY_SCHEMA_VERSION,
    GEOMETRY_AUTHORING_EXPORT_REQUEST_SCHEMA_VERSION,
    GEOMETRY_AUTHORING_FAILURE_SCHEMA_VERSION,
    GEOMETRY_AUTHORING_RECEIPT_SCHEMA_VERSION,
    GEOMETRY_AUTHORING_REQUEST_SCHEMA_VERSION,
    GEOMETRY_AUTHORING_REVISION_REQUEST_SCHEMA_VERSION,
    GEOMETRY_SOURCE_SCHEMA_VERSION,
    ArtifactJsonGeometryAuthoringProvider,
    GeometryArtifactBinding,
    GeometryAuthoringCapabilityReport,
    GeometryAuthoringExportRequest,
    GeometryAuthoringFailure,
    GeometryAuthoringInputDrift,
    GeometryAuthoringInvalidResponse,
    GeometryAuthoringOperation,
    GeometryAuthoringParameterValue,
    GeometryAuthoringProvider,
    GeometryAuthoringProviderError,
    GeometryAuthoringProviderIdentity,
    GeometryAuthoringProviderReceipt,
    GeometryAuthoringReference,
    GeometryAuthoringRequest,
    GeometryAuthoringRequestContract,
    GeometryAuthoringRevisionRequest,
    GeometryCoordinateSystem,
    GeometryFailureCode,
    GeometryInputModality,
    GeometryPartBinding,
    GeometryRepresentationBinding,
    GeometryRepresentationRole,
    GeometryRightsAssertion,
    GeometrySemanticParameter,
    GeometrySourceBundle,
    GeometrySourceProvenance,
    HttpJsonGeometryAuthoringProvider,
    geometry_authoring_request_digest,
)

__all__ = [
    "GEOMETRY_AUTHORING_CAPABILITY_SCHEMA_VERSION",
    "GEOMETRY_AUTHORING_EXPORT_REQUEST_SCHEMA_VERSION",
    "GEOMETRY_AUTHORING_FAILURE_SCHEMA_VERSION",
    "GEOMETRY_AUTHORING_RECEIPT_SCHEMA_VERSION",
    "GEOMETRY_AUTHORING_REQUEST_SCHEMA_VERSION",
    "GEOMETRY_AUTHORING_REVISION_REQUEST_SCHEMA_VERSION",
    "GEOMETRY_SOURCE_SCHEMA_VERSION",
    "ArtifactJsonGeometryAuthoringProvider",
    "GeometryArtifactBinding",
    "GeometryAuthoringCapabilityReport",
    "GeometryAuthoringExportRequest",
    "GeometryAuthoringFailure",
    "GeometryAuthoringInputDrift",
    "GeometryAuthoringInvalidResponse",
    "GeometryAuthoringOperation",
    "GeometryAuthoringParameterValue",
    "GeometryAuthoringProvider",
    "GeometryAuthoringProviderError",
    "GeometryAuthoringProviderIdentity",
    "GeometryAuthoringProviderReceipt",
    "GeometryAuthoringReference",
    "GeometryAuthoringRequest",
    "GeometryAuthoringRequestContract",
    "GeometryAuthoringRevisionRequest",
    "GeometryCoordinateSystem",
    "GeometryFailureCode",
    "GeometryInputModality",
    "GeometryPartBinding",
    "GeometryRepresentationBinding",
    "GeometryRepresentationRole",
    "GeometryRightsAssertion",
    "GeometrySemanticParameter",
    "GeometrySourceBundle",
    "GeometrySourceProvenance",
    "HttpJsonGeometryAuthoringProvider",
    "geometry_authoring_request_digest",
]
