# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Physics authoring workflow contracts for agentic asset workflows."""

from .external_tuning_contract import (
    EXTERNAL_PROMOTABLE_STATUSES,
    EXTERNAL_TUNING_DECISION_SCHEMA_VERSION,
    EXTERNAL_TUNING_RESULT_SCHEMA_VERSION,
    PhysicsExternalReviewedFrame,
    PhysicsExternalSelectedResult,
    PhysicsExternalTuningDecision,
    PhysicsExternalTuningResult,
    load_physics_external_tuning_decision,
    load_physics_external_tuning_result,
    verify_external_decision_chain,
)
from .policy import (
    PhysicsMaterialProfile,
    infer_material_profile,
    material_volume_fractions,
    physics_policy_prompt,
)
from .preflight import (
    PHYSICS_RUNTIME_PREFLIGHT_SCHEMA_VERSION,
    PhysicsRuntimePreflightReport,
    preflight_ovphysx_runtime,
)
from .tuning_contract import (
    PROMOTABLE_STATUSES,
    TUNING_DECISION_SCHEMA_VERSION,
    TUNING_RESULT_SCHEMA_VERSION,
    PhysicsTuningDecision,
    PhysicsTuningResult,
    PhysicsTuningSelectedCandidate,
    load_physics_tuning_decision,
    load_physics_tuning_result,
    verify_decision_chain,
)
from .vomp import (
    PHYSICS_VOMP_RESULT_SCHEMA_VERSION,
    PhysicsVompMassConfig,
    PhysicsVompMassResult,
    resolve_vomp_target_prim,
    run_agentic_vomp_mass_authoring,
    verify_vomp_mass_properties,
    vomp_contract_payload,
)
from .workflow import (
    PhysicsApplyWorkflowInput,
    PhysicsApplyWorkflowResult,
    PhysicsBehaviorAssessment,
    PhysicsCandidate,
    PhysicsComponent,
    PhysicsComponentDecision,
    PhysicsComponentTargetDecision,
    PhysicsConvexDecompositionOptions,
    PhysicsDecision,
    add_physics_component_target_catalog,
    default_physics_behavior_assessment,
    infer_component_decisions,
    infer_physics_decisions,
    inspect_mesh_prims,
    inspect_physics_components,
    load_physics_behavior_assessment,
    load_physics_decision_patch,
    merge_physics_behavior_assessment,
    parse_physics_component_catalog_entry,
    parse_physics_decision_patch,
    physics_decision_assignment_payload,
    rebase_physics_v2_patch_to_components,
    resolve_physics_v2_patch_targets,
    run_physics_apply_workflow,
    validate_physics_runtime,
)

__all__ = [
    "EXTERNAL_PROMOTABLE_STATUSES",
    "EXTERNAL_TUNING_DECISION_SCHEMA_VERSION",
    "EXTERNAL_TUNING_RESULT_SCHEMA_VERSION",
    "PhysicsApplyWorkflowInput",
    "PhysicsExternalReviewedFrame",
    "PhysicsExternalSelectedResult",
    "PhysicsExternalTuningDecision",
    "PhysicsExternalTuningResult",
    "load_physics_external_tuning_decision",
    "load_physics_external_tuning_result",
    "verify_external_decision_chain",
    "PhysicsApplyWorkflowResult",
    "PhysicsBehaviorAssessment",
    "PhysicsCandidate",
    "PhysicsComponent",
    "PhysicsComponentDecision",
    "PhysicsComponentTargetDecision",
    "PhysicsConvexDecompositionOptions",
    "PhysicsDecision",
    "PhysicsMaterialProfile",
    "PhysicsRuntimePreflightReport",
    "PHYSICS_RUNTIME_PREFLIGHT_SCHEMA_VERSION",
    "PROMOTABLE_STATUSES",
    "TUNING_DECISION_SCHEMA_VERSION",
    "TUNING_RESULT_SCHEMA_VERSION",
    "PhysicsTuningDecision",
    "PhysicsTuningResult",
    "PhysicsTuningSelectedCandidate",
    "add_physics_component_target_catalog",
    "PHYSICS_VOMP_RESULT_SCHEMA_VERSION",
    "PhysicsVompMassConfig",
    "PhysicsVompMassResult",
    "default_physics_behavior_assessment",
    "infer_material_profile",
    "material_volume_fractions",
    "infer_physics_decisions",
    "infer_component_decisions",
    "inspect_physics_components",
    "inspect_mesh_prims",
    "load_physics_behavior_assessment",
    "load_physics_decision_patch",
    "parse_physics_component_catalog_entry",
    "parse_physics_decision_patch",
    "physics_decision_assignment_payload",
    "rebase_physics_v2_patch_to_components",
    "resolve_physics_v2_patch_targets",
    "load_physics_tuning_decision",
    "load_physics_tuning_result",
    "verify_decision_chain",
    "merge_physics_behavior_assessment",
    "physics_policy_prompt",
    "preflight_ovphysx_runtime",
    "run_physics_apply_workflow",
    "resolve_vomp_target_prim",
    "run_agentic_vomp_mass_authoring",
    "validate_physics_runtime",
    "verify_vomp_mass_properties",
    "vomp_contract_payload",
]
