{{- if and (not .Values.existingApiKeySecretName) .Values.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "geometry-agent-service.apiSecretName" . }}
  labels:
    {{- include "geometry-agent-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-key: {{ .Values.apiKey | quote }}
{{- end }}
