# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""Joint Agent Functions."""

from joint_agent.functions.analytic_gprim_normalization import (
    ANALYTIC_GPRIM_COLLIDER_CHILD_NAME,
    ANALYTIC_GPRIM_NORMALIZATION_VERSION,
    ANALYTIC_GPRIM_RECEIPT_SCHEMA_VERSION,
    ANALYTIC_GPRIM_RENDER_CHILD_NAME,
    AnalyticGprimNormalizationError,
    AnalyticGprimNormalizationResult,
    normalize_analytic_cube_gprims,
)
from joint_agent.functions.articulation_contract import (
    ARTICULATION_CONTRACT_SCHEMA_VERSION,
    ArticulationContractV1,
    ArticulationRecordV1,
    BodyAuthoring,
    ContractDiagnosticV1,
    ContractSummaryV1,
    DiagnosticSeverity,
    JointRecordV1,
    LinkRecordV1,
    LinkRole,
    PrimRecordV1,
)
from joint_agent.functions.articulation_contract_stage2 import (
    build_articulation_contract_from_stage2,
)
from joint_agent.functions.articulation_contract_v2 import (
    ARTICULATION_CONTRACT_V2_IMPLEMENTED_CAPABILITY_IDS,
    ARTICULATION_CONTRACT_V2_SCHEMA_VERSION,
    ArticulationContractV2,
    ArticulationContractV2Error,
    AttachmentFrameV2,
    Body1OriginAttachmentDefaultV2,
    DistanceConstraintV2,
    ExplicitAttachmentFramesV2,
    FieldEvidenceV2,
    FixedConstraintV2,
    JointRecordV2,
    PrismaticConstraintV2,
    RevoluteConstraintV2,
    SphericalConstraintV2,
    attachment_frame_from_basis_v2,
    canonical_articulation_v2_json,
    canonical_articulation_v2_sha256,
    convert_articulation_v1_to_v2,
    downgrade_articulation_v2_to_v1,
    negotiate_articulation_contract_v2,
    parse_articulation_contract_v2,
)
from joint_agent.functions.articulation_types import ArticulationReviewStatus
from joint_agent.functions.articulation_v2_controlled_distance import (
    CONTROLLED_DISTANCE_BASE_FIELD_PROPERTIES,
    CONTROLLED_DISTANCE_FIELD_PROPERTIES,
    CONTROLLED_DISTANCE_SCHEMA_VERSION,
    CONTROLLED_DISTANCE_SCHEMA_VERSION_V2,
    ControlledDistanceContractV1,
    ControlledDistanceContractV2,
    ControlledDistanceError,
    DistanceLinearDriveV1,
    DistanceLinearStateV1,
    bind_controlled_distance_contract_v1,
    bind_controlled_distance_contract_v2,
    canonical_controlled_distance_json,
    canonical_controlled_distance_sha256,
    canonical_controlled_distance_v2_json,
    canonical_controlled_distance_v2_sha256,
    parse_controlled_distance_contract_v1,
    parse_controlled_distance_contract_v2,
)
from joint_agent.functions.consistency import apply_prediction_consistency
from joint_agent.functions.inference import batch_classify_assets, classify_asset
from joint_agent.functions.joint_rigger_contract_bridge import (
    build_joint_rigger_input_from_contract,
)
from joint_agent.functions.joint_rigger_gate3_plan import (
    GATE3_PHYSICS_PLAN_ENVELOPE_SCHEMA_VERSION,
    Gate3PhysicsPlanEnvelopeV1,
    build_gate3_joint_rigger_input_from_contract,
)
from joint_agent.functions.joint_rigger_gate3_policy import (
    GATE3_PHYSICS_POLICY_SCHEMA_VERSION,
    SUPPORTED_COLLIDER_PRIM_TYPES,
    ColliderPrimType,
    Gate3PhysicsPolicyV1,
    produce_owner_approved_gate3_joint_rigger_input,
)
from joint_agent.functions.membership_disposition import (
    MEMBERSHIP_DISPOSITION_SCHEMA_VERSION,
    MembershipDispositionDocument,
    MembershipDispositionRecord,
    infer_membership_dispositions,
    membership_disposition_json_schema,
    membership_disposition_sha256,
)
from joint_agent.functions.physics_schema_authoring import author_physics_schemas
from joint_agent.functions.rigged_reference_validation import (
    compare_articulation_candidates_to_reference,
    extract_reference_articulation_manifest,
    normalize_reference_connections,
    write_rigged_reference_validation_report_html,
)
from joint_agent.functions.stage1_schema import (
    Stage1PredictionContract,
    has_parseable_stage1_source_response,
    normalize_stage1_prediction_payload,
    stage1_prediction_json_schema,
    unwrap_stage1_prediction_payload,
    validate_stage1_prediction_payload,
)

__all__ = [
    "ANALYTIC_GPRIM_COLLIDER_CHILD_NAME",
    "ANALYTIC_GPRIM_NORMALIZATION_VERSION",
    "ANALYTIC_GPRIM_RECEIPT_SCHEMA_VERSION",
    "ANALYTIC_GPRIM_RENDER_CHILD_NAME",
    "ARTICULATION_CONTRACT_SCHEMA_VERSION",
    "ARTICULATION_CONTRACT_V2_IMPLEMENTED_CAPABILITY_IDS",
    "ARTICULATION_CONTRACT_V2_SCHEMA_VERSION",
    "CONTROLLED_DISTANCE_BASE_FIELD_PROPERTIES",
    "CONTROLLED_DISTANCE_FIELD_PROPERTIES",
    "CONTROLLED_DISTANCE_SCHEMA_VERSION",
    "CONTROLLED_DISTANCE_SCHEMA_VERSION_V2",
    "AnalyticGprimNormalizationError",
    "AnalyticGprimNormalizationResult",
    "GATE3_PHYSICS_POLICY_SCHEMA_VERSION",
    "GATE3_PHYSICS_PLAN_ENVELOPE_SCHEMA_VERSION",
    "MEMBERSHIP_DISPOSITION_SCHEMA_VERSION",
    "SUPPORTED_COLLIDER_PRIM_TYPES",
    "ArticulationContractV1",
    "ArticulationContractV2",
    "ArticulationContractV2Error",
    "ArticulationRecordV1",
    "ArticulationReviewStatus",
    "AttachmentFrameV2",
    "BodyAuthoring",
    "Body1OriginAttachmentDefaultV2",
    "ColliderPrimType",
    "ContractDiagnosticV1",
    "ContractSummaryV1",
    "ControlledDistanceContractV1",
    "ControlledDistanceContractV2",
    "ControlledDistanceError",
    "DiagnosticSeverity",
    "DistanceConstraintV2",
    "DistanceLinearDriveV1",
    "DistanceLinearStateV1",
    "ExplicitAttachmentFramesV2",
    "FieldEvidenceV2",
    "FixedConstraintV2",
    "Gate3PhysicsPolicyV1",
    "Gate3PhysicsPlanEnvelopeV1",
    "JointRecordV1",
    "JointRecordV2",
    "LinkRole",
    "LinkRecordV1",
    "MembershipDispositionDocument",
    "MembershipDispositionRecord",
    "PrimRecordV1",
    "PrismaticConstraintV2",
    "RevoluteConstraintV2",
    "SphericalConstraintV2",
    "Stage1PredictionContract",
    "apply_prediction_consistency",
    "attachment_frame_from_basis_v2",
    "classify_asset",
    "batch_classify_assets",
    "has_parseable_stage1_source_response",
    "build_joint_rigger_input_from_contract",
    "bind_controlled_distance_contract_v1",
    "bind_controlled_distance_contract_v2",
    "author_physics_schemas",
    "build_articulation_contract_from_stage2",
    "build_gate3_joint_rigger_input_from_contract",
    "compare_articulation_candidates_to_reference",
    "canonical_articulation_v2_json",
    "canonical_articulation_v2_sha256",
    "canonical_controlled_distance_json",
    "canonical_controlled_distance_sha256",
    "canonical_controlled_distance_v2_json",
    "canonical_controlled_distance_v2_sha256",
    "convert_articulation_v1_to_v2",
    "downgrade_articulation_v2_to_v1",
    "extract_reference_articulation_manifest",
    "infer_membership_dispositions",
    "membership_disposition_json_schema",
    "membership_disposition_sha256",
    "normalize_analytic_cube_gprims",
    "normalize_reference_connections",
    "normalize_stage1_prediction_payload",
    "negotiate_articulation_contract_v2",
    "parse_articulation_contract_v2",
    "parse_controlled_distance_contract_v1",
    "parse_controlled_distance_contract_v2",
    "produce_owner_approved_gate3_joint_rigger_input",
    "stage1_prediction_json_schema",
    "unwrap_stage1_prediction_payload",
    "validate_stage1_prediction_payload",
    "write_rigged_reference_validation_report_html",
]
