# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Agent-facing client helpers for Content Workbench."""

from .client import (
    AgentApiDiscovery,
    HealthResponse,
    PathTranslationRequest,
    PhysicsApplySchemaRequest,
    PhysicsApplyTopologyPlanRequest,
    PhysicsInspectRequest,
    PhysicsRuntimeValidationRequest,
    PickRequest,
    RenderFramesRequest,
    RenderRequest,
    SceneRestoreRequest,
    SceneSnapshotRequest,
    SessionCreateRequest,
    WorkbenchHealthConfigurationError,
    apply_command,
    apply_physics_schema,
    apply_physics_topology_plan,
    artifact_url,
    check_health,
    close_session,
    create_session,
    download_agent_api_docs,
    download_render_artifacts,
    download_to_file,
    get_agent_api_discovery,
    get_json,
    get_material_assignments,
    get_material_bindings_batch,
    get_optimization,
    get_optional_json,
    inspect_physics_candidates,
    inspect_physics_components,
    inspect_physics_topology,
    is_healthy,
    normalize_url,
    pick,
    post_json,
    render,
    render_frames,
    render_view,
    request_json,
    restore_scene,
    session_url,
    snapshot_scene,
    translate_paths,
    validate_physics_runtime,
    wait_until_healthy,
)

__all__ = [
    "AgentApiDiscovery",
    "HealthResponse",
    "PathTranslationRequest",
    "PhysicsApplySchemaRequest",
    "PhysicsApplyTopologyPlanRequest",
    "PhysicsInspectRequest",
    "PhysicsRuntimeValidationRequest",
    "PickRequest",
    "RenderFramesRequest",
    "RenderRequest",
    "SceneSnapshotRequest",
    "SceneRestoreRequest",
    "SessionCreateRequest",
    "WorkbenchHealthConfigurationError",
    "__version__",
    "apply_physics_schema",
    "apply_physics_topology_plan",
    "apply_command",
    "artifact_url",
    "check_health",
    "close_session",
    "create_session",
    "download_agent_api_docs",
    "download_render_artifacts",
    "download_to_file",
    "get_agent_api_discovery",
    "get_json",
    "get_material_assignments",
    "get_material_bindings_batch",
    "get_optimization",
    "get_optional_json",
    "inspect_physics_candidates",
    "inspect_physics_components",
    "inspect_physics_topology",
    "is_healthy",
    "normalize_url",
    "pick",
    "post_json",
    "render",
    "render_frames",
    "render_view",
    "request_json",
    "restore_scene",
    "session_url",
    "snapshot_scene",
    "translate_paths",
    "validate_physics_runtime",
    "wait_until_healthy",
]

__version__ = "0.1.0"
