# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""Validation Agent V1 contracts and extension points."""

from world_understanding.validation.evaluation import (
    EVALUATION_SCHEMA_VERSION,
    EvaluationCorrection,
    EvaluationFinding,
    EvaluationResult,
    EvaluationStatus,
    EvaluationSubject,
    material_self_evaluation_result_from_signals,
)
from world_understanding.validation.models import (
    InputKind,
    IssueSeverity,
    PlannerBackend,
    TemplateStatus,
    ValidationEvidence,
    ValidationFocusConfig,
    ValidationInput,
    ValidationInputGroups,
    ValidationIssue,
    ValidationModel,
    ValidationPlan,
    ValidationPlannerConfig,
    ValidationPlanStep,
    ValidationProject,
    ValidationRenderConfig,
    ValidationRequest,
    ValidationResult,
    ValidationTemplateResult,
    ValidationVerdict,
    aggregate_validation_verdict,
)
from world_understanding.validation.rendering_backend_contract import (
    SUPPORTED_RENDER_BACKENDS,
    VALIDATION_RENDERING_BACKEND_NAMES,
)
from world_understanding.validation.runner import (
    ValidationTemplate,
    ValidationTemplateContext,
)
from world_understanding.validation.scaffold_compat import (
    validation_issue_from_scaffold_issue,
    validation_plan_from_scaffold_plan,
    validation_request_from_scaffold_request,
    validation_result_from_scaffold_result,
    validation_template_result_from_scaffold_result,
)
from world_understanding.validation.simready_profile import (
    DEFAULT_FIXTURE_CONFIG_NAME,
    DEFERRED_FIXTURE_STATUSES,
    SimReadyFixtureRequest,
    SimReadyProfileError,
    build_simready_fixture_requests,
    write_simready_fixture_configs,
)
from world_understanding.validation.templates import (
    DEFAULT_TEMPLATE_DEFINITIONS,
    V1_TEMPLATE_NAMES,
    ValidationContractError,
    ValidationTemplateDefinition,
    ValidationTemplateRegistry,
    create_default_template_registry,
)
from world_understanding.validation.usd_rendering import render_usd_visual_evidence
from world_understanding.validation.visual_grounding import (
    CameraSpec,
    MeshRecord,
    generate_visual_grounding_packet,
)

__all__ = [
    "DEFAULT_TEMPLATE_DEFINITIONS",
    "DEFAULT_FIXTURE_CONFIG_NAME",
    "DEFERRED_FIXTURE_STATUSES",
    "EVALUATION_SCHEMA_VERSION",
    "EvaluationCorrection",
    "EvaluationFinding",
    "EvaluationResult",
    "EvaluationStatus",
    "EvaluationSubject",
    "InputKind",
    "IssueSeverity",
    "CameraSpec",
    "MeshRecord",
    "PlannerBackend",
    "SimReadyFixtureRequest",
    "SimReadyProfileError",
    "SUPPORTED_RENDER_BACKENDS",
    "TemplateStatus",
    "V1_TEMPLATE_NAMES",
    "ValidationContractError",
    "ValidationEvidence",
    "ValidationFocusConfig",
    "ValidationInput",
    "ValidationInputGroups",
    "ValidationIssue",
    "ValidationModel",
    "ValidationPlan",
    "ValidationPlanStep",
    "ValidationPlannerConfig",
    "ValidationProject",
    "ValidationRenderConfig",
    "ValidationRequest",
    "ValidationResult",
    "ValidationTemplate",
    "ValidationTemplateContext",
    "ValidationTemplateDefinition",
    "ValidationTemplateRegistry",
    "ValidationTemplateResult",
    "ValidationVerdict",
    "VALIDATION_RENDERING_BACKEND_NAMES",
    "aggregate_validation_verdict",
    "build_simready_fixture_requests",
    "create_default_template_registry",
    "generate_visual_grounding_packet",
    "material_self_evaluation_result_from_signals",
    "render_usd_visual_evidence",
    "validation_issue_from_scaffold_issue",
    "validation_plan_from_scaffold_plan",
    "validation_request_from_scaffold_request",
    "validation_result_from_scaffold_result",
    "validation_template_result_from_scaffold_result",
    "write_simready_fixture_configs",
]
