# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""Dedicated retained-evidence contracts for articulation-v2 static runs.

These inert 0.6 envelopes cross-bind plan, intake, generated byte identities,
and the five admitted stages. They do not read evidence, author USD, execute a
validator, score a result, or publish a root.
"""

from __future__ import annotations

import hashlib
import json
import re
from typing import Any, Literal, TypeVar

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    TypeAdapter,
    field_validator,
    model_validator,
)
from world_understanding.utils.artifacts import validated_artifact_relative_key

from joint_agent.articulation_v2_static_artifact_identity import (
    ArticulationV2StaticGeneratedArtifactIdentitiesV1,
)
from joint_agent.articulation_v2_static_evidence_contracts import (
    STATIC_EVIDENCE_AUTHORING_RESULT_PATH,
    STATIC_EVIDENCE_GATE3_CLOSEOUT_PATH,
    STATIC_EVIDENCE_GATE3_FAILURE_RECEIPT_PATH,
    STATIC_EVIDENCE_GATE3B_SUPPORT_PATH,
    STATIC_EVIDENCE_INTAKE_PATH,
    STATIC_EVIDENCE_RESULT_BUNDLE_PATH,
    STATIC_EVIDENCE_RUN_PLAN_PATH,
    STATIC_EVIDENCE_TERMINAL_RECEIPT_PATH,
    ArticulationV2StaticEvidencePathAllowlistV1,
    articulation_v2_static_gate3a_failure_paths,
    articulation_v2_static_gate3b_failure_paths,
)
from joint_agent.articulation_v2_static_execution_command import (
    articulation_v2_static_command_sha256,
)
from joint_agent.articulation_v2_static_intake import (
    ArticulationV2StaticIntakeV1,
    _revalidate_articulation_v2_static_intake,
    articulation_v2_static_intake_sha256,
    canonical_articulation_v2_static_intake_bytes,
    validate_articulation_v2_static_intake,
)
from joint_agent.articulation_v2_static_run_plan import (
    ArticulationV2StaticRunIdentityV1,
    ArticulationV2StaticRunPlanV1,
    ArticulationV2StaticStagePlanV1,
    _revalidate_articulation_v2_static_run_plan,
    articulation_v2_static_run_plan_sha256,
    canonical_articulation_v2_static_run_plan_bytes,
)
from joint_agent.articulation_v2_static_semantics import (
    ArticulationV2StaticJointSemanticsV1,
)
from joint_agent.capability_manifest import (
    CapabilityManifestError,
    LoadedCapabilityManifest,
)
from joint_agent.static_qualification_contracts import (
    ARTICULATION_V2_STATIC_ADOPTION_SCHEMA_VERSION,
    ARTICULATION_V2_STATIC_AUTHORING_SCHEMA_VERSION,
    ARTICULATION_V2_STATIC_READBACK_SCHEMA_VERSION,
)

ARTICULATION_V2_STATIC_GATE3_CLAIM_SCHEMA_VERSION: Literal[
    "joint-agent-articulation-v2-static-gate3-claim-v1"
] = "joint-agent-articulation-v2-static-gate3-claim-v1"
ARTICULATION_V2_STATIC_GATE3_CLOSEOUT_SCHEMA_VERSION: Literal[
    "joint-agent-articulation-v2-static-gate3-closeout-v1"
] = "joint-agent-articulation-v2-static-gate3-closeout-v1"
ARTICULATION_V2_STATIC_RESULT_BUNDLE_SCHEMA_VERSION: Literal[
    "joint-agent-articulation-v2-static-result-bundle-v1"
] = "joint-agent-articulation-v2-static-result-bundle-v1"
ARTICULATION_V2_STATIC_COMPLETION_SCHEMA_VERSION: Literal[
    "joint-agent-articulation-v2-static-completion-v1"
] = "joint-agent-articulation-v2-static-completion-v1"
ARTICULATION_V2_STATIC_GATE3_FAILURE_SCHEMA_VERSION: Literal[
    "joint-agent-articulation-v2-static-gate3-failure-v1"
] = "joint-agent-articulation-v2-static-gate3-failure-v1"

type ReceiptStatus = Literal["pass", "fail", "error"]
_SHA256_RE = re.compile(r"^[0-9a-f]{64}$")


class _ReceiptModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        frozen=True,
        strict=True,
        revalidate_instances="always",
    )


class StaticReceiptFileV1(_ReceiptModel):
    """Exact retained file identity, with no file access behavior."""

    path: str
    size_bytes: int = Field(gt=0)
    sha256: str

    @field_validator("path")
    @classmethod
    def _canonical_path(cls, value: str) -> str:
        try:
            canonical: str = validated_artifact_relative_key(value)
        except ValueError as exc:
            raise ValueError("receipt path must be canonical and relative") from exc
        return canonical

    @field_validator("sha256")
    @classmethod
    def _lowercase_sha256(cls, value: str) -> str:
        return _require_sha256(value, "receipt file sha256")


class ArticulationV2StaticEvidenceBindingV1(_ReceiptModel):
    """Pre-execution identity tuple required unchanged by every stage."""

    run_plan_sha256: str
    intake_sha256: str
    run: ArticulationV2StaticRunIdentityV1

    @field_validator("run_plan_sha256", "intake_sha256")
    @classmethod
    def _lowercase_sha256(cls, value: str, info: Any) -> str:
        return _require_sha256(value, info.field_name)


class ArticulationV2StaticReceiptStageV1(_ReceiptModel):
    """One exact planned stage plus the digest of its canonical command."""

    plan: ArticulationV2StaticStagePlanV1
    command_sha256: str

    @field_validator("command_sha256")
    @classmethod
    def _lowercase_sha256(cls, value: str) -> str:
        return _require_sha256(value, "command_sha256")

    @model_validator(mode="after")
    def _command_digest_matches(self) -> ArticulationV2StaticReceiptStageV1:
        if self.command_sha256 != articulation_v2_static_command_sha256(
            self.plan.command
        ):
            raise ValueError("stage command digest differs from canonical command")
        return self


class ArticulationV2StaticAdoptionReceiptV1(_ReceiptModel):
    """Dedicated 0.6 receipt for the admitted semantic contract."""

    schema_version: Literal["joint-agent-articulation-v2-static-adoption-v1"]
    binding: ArticulationV2StaticEvidenceBindingV1
    stage: ArticulationV2StaticReceiptStageV1
    status: ReceiptStatus
    contract_file: StaticReceiptFileV1
    selector_semantics_sha256: str

    @field_validator("selector_semantics_sha256")
    @classmethod
    def _lowercase_sha256(cls, value: str) -> str:
        return _require_sha256(value, "selector_semantics_sha256")

    @model_validator(mode="after")
    def _contract_stage(self) -> ArticulationV2StaticAdoptionReceiptV1:
        if self.stage.plan.stage != "contract":
            raise ValueError("adoption receipt requires the contract stage")
        return self


class ArticulationV2StaticAuthoringReceiptV1(_ReceiptModel):
    """Dedicated 0.6 receipt for retained authoring output, when present."""

    schema_version: Literal["joint-agent-articulation-v2-static-authoring-v1"]
    binding: ArticulationV2StaticEvidenceBindingV1
    stage: ArticulationV2StaticReceiptStageV1
    status: ReceiptStatus
    adoption_receipt_sha256: str
    authoring_result: StaticReceiptFileV1
    generated_file: StaticReceiptFileV1 | None = None
    generated_identities: ArticulationV2StaticGeneratedArtifactIdentitiesV1 | None = (
        None
    )

    @field_validator("adoption_receipt_sha256")
    @classmethod
    def _lowercase_sha256(cls, value: str) -> str:
        return _require_sha256(value, "adoption_receipt_sha256")

    @model_validator(mode="after")
    def _authoring_stage_and_optional_bytes(
        self,
    ) -> ArticulationV2StaticAuthoringReceiptV1:
        if self.stage.plan.stage != "authoring":
            raise ValueError("authoring receipt requires the authoring stage")
        if self.authoring_result.path != STATIC_EVIDENCE_AUTHORING_RESULT_PATH:
            raise ValueError("authoring result uses an unadmitted evidence path")
        if (self.generated_file is None) != (self.generated_identities is None):
            raise ValueError(
                "generated file and dual identities must appear only together"
            )
        if self.status == "pass" and self.generated_identities is None:
            raise ValueError("passing authoring requires retained generated bytes")
        if self.generated_file is not None and self.generated_identities is not None:
            _require_generated_file_matches_identities(
                self.generated_file,
                self.generated_identities,
            )
        return self


class ArticulationV2StaticComparisonChecksV1(_ReceiptModel):
    capability: bool
    selector: bool
    source_authority: bool
    endpoints: bool
    attachment_frames: bool
    constraint: bool

    @property
    def passed(self) -> bool:
        return all(self.model_dump(mode="python").values())


class ArticulationV2StaticReadbackReceiptV1(_ReceiptModel):
    """Dedicated substantive saved-stage comparison for fixed/distance output."""

    schema_version: Literal["joint-agent-articulation-v2-static-readback-v1"]
    binding: ArticulationV2StaticEvidenceBindingV1
    stage: ArticulationV2StaticReceiptStageV1
    status: Literal["pass", "fail"]
    authoring_receipt_sha256: str
    generated_file: StaticReceiptFileV1
    generated_identities: ArticulationV2StaticGeneratedArtifactIdentitiesV1
    expected: ArticulationV2StaticJointSemanticsV1
    observed: ArticulationV2StaticJointSemanticsV1
    checks: ArticulationV2StaticComparisonChecksV1

    @field_validator("authoring_receipt_sha256")
    @classmethod
    def _lowercase_sha256(cls, value: str) -> str:
        return _require_sha256(value, "authoring_receipt_sha256")

    @model_validator(mode="after")
    def _substantive_readback(self) -> ArticulationV2StaticReadbackReceiptV1:
        if self.stage.plan.stage != "readback":
            raise ValueError("readback receipt requires the readback stage")
        _require_generated_file_matches_identities(
            self.generated_file,
            self.generated_identities,
        )
        expected_checks = articulation_v2_static_comparison_checks(
            self.expected,
            self.observed,
        )
        if self.checks != expected_checks:
            raise ValueError("readback checks differ from substantive comparison")
        if expected_checks.passed != (self.expected == self.observed):
            raise ValueError("readback checks do not exhaust the semantic contract")
        expected_status = "pass" if expected_checks.passed else "fail"
        if self.status != expected_status:
            raise ValueError("readback status differs from substantive comparison")
        return self


class ArticulationV2StaticGate3ClaimV1(_ReceiptModel):
    """Retained Gate 3 claim; execution and closeout are owned elsewhere."""

    schema_version: Literal["joint-agent-articulation-v2-static-gate3-claim-v1"]
    binding: ArticulationV2StaticEvidenceBindingV1
    stage: ArticulationV2StaticReceiptStageV1
    status: ReceiptStatus
    readback_receipt_sha256: str
    generated_file: StaticReceiptFileV1
    generated_identities: ArticulationV2StaticGeneratedArtifactIdentitiesV1
    raw_report: StaticReceiptFileV1
    stdout_log: StaticReceiptFileV1
    stderr_log: StaticReceiptFileV1
    support_evidence: StaticReceiptFileV1 | None = None

    @field_validator("readback_receipt_sha256")
    @classmethod
    def _lowercase_sha256(cls, value: str) -> str:
        return _require_sha256(value, "readback_receipt_sha256")

    @model_validator(mode="after")
    def _gate3_stage(self) -> ArticulationV2StaticGate3ClaimV1:
        stage = self.stage.plan.stage
        if stage not in {"gate3a", "gate3b"}:
            raise ValueError("Gate 3 claim requires gate3a or gate3b stage")
        if self.raw_report.path != f"reports/{stage}.json":
            raise ValueError(f"{stage} raw report uses an unadmitted evidence path")
        if self.stdout_log.path != f"logs/{stage}.stdout.json":
            raise ValueError(f"{stage} stdout log uses an unadmitted evidence path")
        if self.stderr_log.path != f"logs/{stage}.stderr.json":
            raise ValueError(f"{stage} stderr log uses an unadmitted evidence path")
        if stage == "gate3a" and self.support_evidence is not None:
            raise ValueError("Gate 3A claim cannot carry Gate 3B support evidence")
        if stage == "gate3b" and (
            self.support_evidence is None
            or self.support_evidence.path != STATIC_EVIDENCE_GATE3B_SUPPORT_PATH
        ):
            raise ValueError("Gate 3B claim requires retained support evidence")
        _require_generated_file_matches_identities(
            self.generated_file,
            self.generated_identities,
        )
        return self


class ArticulationV2StaticResultBundleV1(_ReceiptModel):
    """Exact five-stage envelope consumed by later closeout and scoring."""

    schema_version: Literal["joint-agent-articulation-v2-static-result-bundle-v1"]
    adoption: ArticulationV2StaticAdoptionReceiptV1
    authoring: ArticulationV2StaticAuthoringReceiptV1
    readback: ArticulationV2StaticReadbackReceiptV1
    gate3a: ArticulationV2StaticGate3ClaimV1
    gate3b: ArticulationV2StaticGate3ClaimV1

    @model_validator(mode="after")
    def _one_identity_and_hash_chain(self) -> ArticulationV2StaticResultBundleV1:
        receipts = (
            self.adoption,
            self.authoring,
            self.readback,
            self.gate3a,
            self.gate3b,
        )
        if any(item.binding != self.adoption.binding for item in receipts[1:]):
            raise ValueError("all five stages must carry one evidence identity tuple")
        if tuple(item.stage.plan.stage for item in receipts) != (
            "contract",
            "authoring",
            "readback",
            "gate3a",
            "gate3b",
        ):
            raise ValueError("result bundle stages are incomplete or substituted")
        if self.authoring.adoption_receipt_sha256 != (
            articulation_v2_static_receipt_sha256(self.adoption)
        ):
            raise ValueError("authoring receipt does not bind the adoption receipt")
        if self.readback.authoring_receipt_sha256 != (
            articulation_v2_static_receipt_sha256(self.authoring)
        ):
            raise ValueError("readback receipt does not bind the authoring receipt")
        readback_sha256 = articulation_v2_static_receipt_sha256(self.readback)
        if any(
            claim.readback_receipt_sha256 != readback_sha256
            for claim in (self.gate3a, self.gate3b)
        ):
            raise ValueError("Gate 3 claims do not bind the readback receipt")
        if self.adoption.status != "pass" and self.authoring.status == "pass":
            raise ValueError("passing authoring requires passing contract adoption")
        if self.authoring.status != "pass" and self.readback.status == "pass":
            raise ValueError("passing readback requires passing authoring")
        if self.readback.status != "pass" and any(
            claim.status == "pass" for claim in (self.gate3a, self.gate3b)
        ):
            raise ValueError("passing Gate 3 requires passing saved-stage readback")
        if any(
            receipt.status != "pass"
            for receipt in (self.adoption, self.authoring, self.readback)
        ):
            raise ValueError(
                "complete result bundle requires passing contract, authoring, "
                "and readback stages"
            )
        if any(claim.status == "error" for claim in (self.gate3a, self.gate3b)):
            raise ValueError("complete result bundle rejects Gate 3 execution errors")
        generated = self.authoring.generated_identities
        generated_file = self.authoring.generated_file
        if generated is None or generated_file is None:
            raise ValueError("five-stage bundle requires retained authoring bytes")
        later = (self.readback, self.gate3a, self.gate3b)
        if any(
            item.generated_identities != generated
            or item.generated_file != generated_file
            for item in later
        ):
            raise ValueError(
                "readback and Gate 3 must reuse both authoring identity domains"
            )
        return self


class ArticulationV2StaticCompletionReceiptV1(_ReceiptModel):
    """Terminal inventory receipt for every allowed pre-completion file."""

    schema_version: Literal["joint-agent-articulation-v2-static-completion-v1"]
    binding: ArticulationV2StaticEvidenceBindingV1
    evidence_paths: ArticulationV2StaticEvidencePathAllowlistV1
    generated_file: StaticReceiptFileV1
    generated_identities: ArticulationV2StaticGeneratedArtifactIdentitiesV1
    result_bundle: StaticReceiptFileV1
    retained_files: tuple[StaticReceiptFileV1, ...]
    terminal_receipt_path: Literal["completion.json"]

    @field_validator("retained_files")
    @classmethod
    def _canonical_file_inventory(
        cls,
        value: tuple[StaticReceiptFileV1, ...],
    ) -> tuple[StaticReceiptFileV1, ...]:
        paths = tuple(item.path for item in value)
        if paths != tuple(sorted(paths)):
            raise ValueError("completion retained file inventory must be sorted")
        if len(paths) != len(set(paths)):
            raise ValueError("completion retained file paths must be unique")
        if STATIC_EVIDENCE_TERMINAL_RECEIPT_PATH in paths:
            raise ValueError("completion receipt cannot inventory itself")
        return value

    @model_validator(mode="after")
    def _exact_non_circular_inventory(
        self,
    ) -> ArticulationV2StaticCompletionReceiptV1:
        if self.terminal_receipt_path != self.evidence_paths.terminal_receipt:
            raise ValueError("completion terminal path differs from the allowlist")
        if tuple(item.path for item in self.retained_files) != (
            self.evidence_paths.retained_paths
        ):
            raise ValueError("completion inventory differs from evidence allowlist")
        by_path = {item.path: item for item in self.retained_files}
        _require_generated_file_matches_identities(
            self.generated_file,
            self.generated_identities,
        )
        if by_path.get(self.generated_file.path) != self.generated_file:
            raise ValueError("completion output identity is absent from inventory")
        if (
            self.result_bundle.path != STATIC_EVIDENCE_RESULT_BUNDLE_PATH
            or by_path.get(self.result_bundle.path) != self.result_bundle
        ):
            raise ValueError("completion result bundle is absent from inventory")
        return self


class ArticulationV2StaticGate3FailureReceiptV1(_ReceiptModel):
    """Terminal, non-qualifying receipt for a missing Gate 3 report."""

    schema_version: Literal["joint-agent-articulation-v2-static-gate3-failure-v1"]
    binding: ArticulationV2StaticEvidenceBindingV1
    stage: ArticulationV2StaticReceiptStageV1
    status: Literal["error"]
    failure_code: Literal[
        "articulation_v2_static_gate3a_report_missing_after_exit",
        "articulation_v2_static_gate3b_report_missing_after_exit",
    ]
    failure_detail: str
    report_observation: Literal["missing"]
    expected_report_path: Literal["reports/gate3a.json", "reports/gate3b.json"]
    returncode: int = Field(ge=-255, le=255)
    termination_reason: Literal[
        "exited",
        "outer_deadline_exceeded",
        "output_limit_exceeded",
        "containment_failure",
    ]
    generated_file: StaticReceiptFileV1
    generated_identities: ArticulationV2StaticGeneratedArtifactIdentitiesV1
    stdout_log: StaticReceiptFileV1
    stderr_log: StaticReceiptFileV1
    retained_files: tuple[StaticReceiptFileV1, ...]
    terminal_receipt_path: Literal["failure.json"]
    static_qualified: Literal[False]
    dynamic_qualified: Literal[False]
    public_enabled: Literal[False]
    release_selection_applied: Literal[False]
    capability_manifest_updated: Literal[False]

    @field_validator("failure_detail")
    @classmethod
    def _bounded_failure_detail(cls, value: str) -> str:
        if not value or len(value) > 4096 or "\x00" in value:
            raise ValueError("Gate 3 failure detail must be nonempty and bounded")
        return value

    @field_validator("retained_files")
    @classmethod
    def _canonical_failure_inventory(
        cls,
        value: tuple[StaticReceiptFileV1, ...],
    ) -> tuple[StaticReceiptFileV1, ...]:
        paths = tuple(item.path for item in value)
        if paths != tuple(sorted(paths)) or len(paths) != len(set(paths)):
            raise ValueError("Gate 3 failure inventory must be sorted and unique")
        if STATIC_EVIDENCE_GATE3_FAILURE_RECEIPT_PATH in paths:
            raise ValueError("Gate 3 failure receipt cannot inventory itself")
        return value

    @model_validator(mode="after")
    def _exact_gate3_failure(self) -> ArticulationV2StaticGate3FailureReceiptV1:
        stage = self.stage.plan.stage
        if stage not in {"gate3a", "gate3b"}:
            raise ValueError("Gate 3 failure receipt requires a Gate 3 stage")
        _require_generated_file_matches_identities(
            self.generated_file,
            self.generated_identities,
        )
        expected_code = f"articulation_v2_static_{stage}_report_missing_after_exit"
        expected_report = f"reports/{stage}.json"
        expected_stdout = f"logs/{stage}.stdout.json"
        expected_stderr = f"logs/{stage}.stderr.json"
        if self.failure_code != expected_code:
            raise ValueError("Gate 3 failure code differs from its stage")
        if self.expected_report_path != expected_report:
            raise ValueError("Gate 3 expected report differs from its stage")
        if self.stdout_log.path != expected_stdout:
            raise ValueError("Gate 3 failure stdout uses an unadmitted path")
        if self.stderr_log.path != expected_stderr:
            raise ValueError("Gate 3 failure stderr uses an unadmitted path")
        path_builder = (
            articulation_v2_static_gate3a_failure_paths
            if stage == "gate3a"
            else articulation_v2_static_gate3b_failure_paths
        )
        expected_paths = path_builder(
            constraint_kind=self.binding.run.selector.constraint_kind,
            generated_output=self.generated_file.path,
        )
        retained_paths = tuple(
            path
            for path in expected_paths
            if path != STATIC_EVIDENCE_GATE3_FAILURE_RECEIPT_PATH
        )
        if tuple(item.path for item in self.retained_files) != retained_paths:
            raise ValueError("Gate 3 failure inventory differs from the contract")
        by_path = {item.path: item for item in self.retained_files}
        if by_path.get(self.generated_file.path) != self.generated_file:
            raise ValueError("Gate 3 failure output identity is absent from inventory")
        if by_path.get(self.stdout_log.path) != self.stdout_log:
            raise ValueError("Gate 3 failure stdout identity is absent from inventory")
        if by_path.get(self.stderr_log.path) != self.stderr_log:
            raise ValueError("Gate 3 failure stderr identity is absent from inventory")
        return self


type ArticulationV2StaticReceipt = (
    ArticulationV2StaticAdoptionReceiptV1
    | ArticulationV2StaticAuthoringReceiptV1
    | ArticulationV2StaticReadbackReceiptV1
    | ArticulationV2StaticGate3ClaimV1
)


def articulation_v2_static_comparison_checks(
    expected: ArticulationV2StaticJointSemanticsV1,
    observed: ArticulationV2StaticJointSemanticsV1,
) -> ArticulationV2StaticComparisonChecksV1:
    """Compare the complete normalized saved-stage semantics without I/O."""

    if (
        type(expected) is not ArticulationV2StaticJointSemanticsV1
        or type(observed) is not ArticulationV2StaticJointSemanticsV1
    ):
        raise TypeError("comparison inputs must use the exact static semantic model")
    return ArticulationV2StaticComparisonChecksV1(
        capability=expected.capability_id == observed.capability_id,
        selector=(
            expected.transform_version == observed.transform_version
            and expected.source_semantic_preimage_sha256
            == observed.source_semantic_preimage_sha256
            and expected.release_gate_asset_id == observed.release_gate_asset_id
            and expected.selector_type == observed.selector_type
            and expected.source_joint_path == observed.source_joint_path
            and expected.joint_id == observed.joint_id
            and expected.topology_decision == observed.topology_decision
            and expected.source_stage_default_prim == observed.source_stage_default_prim
            and expected.source_stage_meters_per_unit
            == observed.source_stage_meters_per_unit
            and expected.source_stage_up_axis == observed.source_stage_up_axis
            and expected.linear_unit_interpretation
            == observed.linear_unit_interpretation
            and expected.orientation_interpretation
            == observed.orientation_interpretation
        ),
        source_authority=expected.source_authority == observed.source_authority,
        endpoints=(
            expected.body0_link_id == observed.body0_link_id
            and expected.body1_link_id == observed.body1_link_id
            and expected.body0_prim_path == observed.body0_prim_path
            and expected.body1_prim_path == observed.body1_prim_path
        ),
        attachment_frames=expected.attachments == observed.attachments,
        constraint=expected.constraint == observed.constraint,
    )


_ModelT = TypeVar("_ModelT", bound=BaseModel)


def _canonical_model_bytes(value: _ModelT, model_type: type[_ModelT]) -> bytes:
    if type(value) is not model_type:
        raise TypeError(f"value must be an exact {model_type.__name__}")
    adapter = TypeAdapter(model_type)
    encoded = json.dumps(
        adapter.dump_python(value, mode="json"),
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
        allow_nan=False,
    ).encode("utf-8")
    validated = adapter.validate_json(encoded, strict=True)
    return json.dumps(
        adapter.dump_python(validated, mode="json"),
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
        allow_nan=False,
    ).encode("utf-8")


def canonical_articulation_v2_static_receipt_bytes(
    receipt: ArticulationV2StaticReceipt,
) -> bytes:
    allowed = (
        ArticulationV2StaticAdoptionReceiptV1,
        ArticulationV2StaticAuthoringReceiptV1,
        ArticulationV2StaticReadbackReceiptV1,
        ArticulationV2StaticGate3ClaimV1,
    )
    if type(receipt) not in allowed:
        raise TypeError("receipt must be an exact articulation-v2 static receipt")
    return _canonical_model_bytes(receipt, type(receipt))


def articulation_v2_static_receipt_sha256(
    receipt: ArticulationV2StaticReceipt,
) -> str:
    return hashlib.sha256(
        canonical_articulation_v2_static_receipt_bytes(receipt)
    ).hexdigest()


def canonical_articulation_v2_static_result_bundle_bytes(
    bundle: ArticulationV2StaticResultBundleV1,
) -> bytes:
    return _canonical_model_bytes(bundle, ArticulationV2StaticResultBundleV1)


def canonical_articulation_v2_static_gate3_closeout_bytes(
    plan: ArticulationV2StaticRunPlanV1,
    intake: ArticulationV2StaticIntakeV1,
    generated_identities: ArticulationV2StaticGeneratedArtifactIdentitiesV1,
) -> bytes:
    """Derive the exact retained Gate 3 closeout input from receipt identities."""

    if type(plan) is not ArticulationV2StaticRunPlanV1:
        raise TypeError("Gate 3 closeout plan must use the exact static run plan")
    if type(intake) is not ArticulationV2StaticIntakeV1:
        raise TypeError("Gate 3 closeout intake must use the exact static intake")
    if (
        type(generated_identities)
        is not ArticulationV2StaticGeneratedArtifactIdentitiesV1
    ):
        raise TypeError(
            "Gate 3 closeout identities must use the exact generated identity model"
        )
    gate3 = generated_identities.gate3
    document = {
        "schema_version": ARTICULATION_V2_STATIC_GATE3_CLOSEOUT_SCHEMA_VERSION,
        "run_id": plan.run.run_id,
        "run_plan_sha256": articulation_v2_static_run_plan_sha256(plan),
        "intake_sha256": articulation_v2_static_intake_sha256(intake),
        "generated_artifact": {
            "uri": gate3.uri,
            "root_sha256": gate3.root_sha256,
            "dependency_bundle_schema_version": gate3.dependency_bundle_schema_version,
            "dependency_bundle_sha256": gate3.dependency_bundle_sha256,
            "dependency_bundle_entry_count": gate3.dependency_bundle_entry_count,
        },
        "assets": [
            {
                "asset_id": plan.run.selector.release_gate_asset_id,
                "generated_usd_path": plan.output.output_key,
            }
        ],
    }
    return json.dumps(
        document,
        allow_nan=False,
        ensure_ascii=True,
        separators=(",", ":"),
        sort_keys=True,
    ).encode("utf-8")


def canonical_articulation_v2_static_completion_bytes(
    receipt: ArticulationV2StaticCompletionReceiptV1,
) -> bytes:
    return _canonical_model_bytes(receipt, ArticulationV2StaticCompletionReceiptV1)


def canonical_articulation_v2_static_gate3_failure_bytes(
    receipt: ArticulationV2StaticGate3FailureReceiptV1,
) -> bytes:
    return _canonical_model_bytes(receipt, ArticulationV2StaticGate3FailureReceiptV1)


def articulation_v2_static_completion_sha256(
    receipt: ArticulationV2StaticCompletionReceiptV1,
) -> str:
    return hashlib.sha256(
        canonical_articulation_v2_static_completion_bytes(receipt)
    ).hexdigest()


def validate_articulation_v2_static_result_bundle(
    loaded: LoadedCapabilityManifest,
    plan: ArticulationV2StaticRunPlanV1,
    intake: ArticulationV2StaticIntakeV1,
    bundle: ArticulationV2StaticResultBundleV1,
) -> None:
    """Cross-check a five-stage bundle without filesystem or subprocess work."""

    plan = _revalidate_articulation_v2_static_run_plan(plan)
    intake = _revalidate_articulation_v2_static_intake(intake)
    bundle = _revalidate_articulation_v2_static_result_bundle(bundle)
    validate_articulation_v2_static_intake(loaded, plan, intake)
    expected_binding = _evidence_binding(plan, intake)
    receipts: tuple[ArticulationV2StaticReceipt, ...] = (
        bundle.adoption,
        bundle.authoring,
        bundle.readback,
        bundle.gate3a,
        bundle.gate3b,
    )
    if any(item.binding != expected_binding for item in receipts):
        raise CapabilityManifestError(
            "static result bundle substitutes a run-plan, intake, or source identity"
        )
    for receipt, expected_stage in zip(
        receipts,
        plan.stages.ordered(),
        strict=True,
    ):
        if receipt.stage.plan != expected_stage:
            raise CapabilityManifestError(
                f"static result bundle substitutes the {expected_stage.stage} stage"
            )
    if (
        bundle.adoption.contract_file.path != intake.contract_uri
        or bundle.adoption.contract_file.sha256 != intake.contract_sha256
        or bundle.adoption.contract_file.size_bytes != intake.contract_size_bytes
        or bundle.adoption.selector_semantics_sha256
        != intake.run.selector.expected_joint_semantics_sha256
    ):
        raise CapabilityManifestError(
            "static adoption receipt differs from the exact intake contract"
        )
    if bundle.readback.expected != intake.contract_semantics:
        raise CapabilityManifestError(
            "static readback expected semantics differ from the intake"
        )
    generated = bundle.authoring.generated_identities
    if generated is None or generated.authorer.uri != plan.output.output_key:
        raise CapabilityManifestError(
            "static authoring receipt differs from the planned output locator"
        )


def validate_articulation_v2_static_completion_receipt(
    loaded: LoadedCapabilityManifest,
    plan: ArticulationV2StaticRunPlanV1,
    intake: ArticulationV2StaticIntakeV1,
    bundle: ArticulationV2StaticResultBundleV1,
    completion: ArticulationV2StaticCompletionReceiptV1,
) -> None:
    """Validate the terminal inventory entirely from retained identities."""

    plan = _revalidate_articulation_v2_static_run_plan(plan)
    intake = _revalidate_articulation_v2_static_intake(intake)
    bundle = _revalidate_articulation_v2_static_result_bundle(bundle)
    completion = _revalidate_articulation_v2_static_completion(completion)
    validate_articulation_v2_static_result_bundle(loaded, plan, intake, bundle)
    expected_binding = _evidence_binding(plan, intake)
    if completion.binding != expected_binding:
        raise CapabilityManifestError("static completion substitutes run identity")
    if completion.evidence_paths != plan.evidence_paths:
        raise CapabilityManifestError("static completion substitutes evidence paths")
    if completion.generated_identities != bundle.authoring.generated_identities:
        raise CapabilityManifestError(
            "static completion substitutes generated identity domains"
        )
    if completion.generated_file != bundle.authoring.generated_file:
        raise CapabilityManifestError("static completion substitutes generated bytes")

    expected_files = _expected_completion_files(plan, intake, bundle)
    actual_files = {item.path: item for item in completion.retained_files}
    for path, expected in expected_files.items():
        if actual_files.get(path) != expected:
            raise CapabilityManifestError(
                f"static completion retained identity differs for {path}"
            )


def _revalidate_articulation_v2_static_result_bundle(
    bundle: ArticulationV2StaticResultBundleV1,
) -> ArticulationV2StaticResultBundleV1:
    if type(bundle) is not ArticulationV2StaticResultBundleV1:
        raise CapabilityManifestError(
            "articulation-v2 static results require the exact 0.6 bundle contract"
        )
    try:
        return TypeAdapter(ArticulationV2StaticResultBundleV1).validate_json(
            canonical_articulation_v2_static_result_bundle_bytes(bundle),
            strict=True,
        )
    except (TypeError, ValueError) as exc:
        raise CapabilityManifestError(
            "articulation-v2 static result bundle fails strict invariant revalidation"
        ) from exc


def _revalidate_articulation_v2_static_completion(
    completion: ArticulationV2StaticCompletionReceiptV1,
) -> ArticulationV2StaticCompletionReceiptV1:
    if type(completion) is not ArticulationV2StaticCompletionReceiptV1:
        raise CapabilityManifestError(
            "static completion requires the exact terminal receipt contract"
        )
    try:
        return TypeAdapter(ArticulationV2StaticCompletionReceiptV1).validate_json(
            canonical_articulation_v2_static_completion_bytes(completion),
            strict=True,
        )
    except (TypeError, ValueError) as exc:
        raise CapabilityManifestError(
            "static completion fails strict invariant revalidation"
        ) from exc


def _expected_completion_files(
    plan: ArticulationV2StaticRunPlanV1,
    intake: ArticulationV2StaticIntakeV1,
    bundle: ArticulationV2StaticResultBundleV1,
) -> dict[str, StaticReceiptFileV1]:
    authoring = bundle.authoring
    generated_file = authoring.generated_file
    generated_identities = authoring.generated_identities
    support_evidence = bundle.gate3b.support_evidence
    if generated_file is None or generated_identities is None:
        raise CapabilityManifestError("static completion has no generated bytes")
    if support_evidence is None:
        raise CapabilityManifestError("static completion has no Gate 3B support")
    files = {
        STATIC_EVIDENCE_RUN_PLAN_PATH: _model_file(
            STATIC_EVIDENCE_RUN_PLAN_PATH,
            canonical_articulation_v2_static_run_plan_bytes(plan),
        ),
        STATIC_EVIDENCE_INTAKE_PATH: StaticReceiptFileV1(
            path=STATIC_EVIDENCE_INTAKE_PATH,
            size_bytes=len(canonical_articulation_v2_static_intake_bytes(intake)),
            sha256=articulation_v2_static_intake_sha256(intake),
        ),
        STATIC_EVIDENCE_GATE3_CLOSEOUT_PATH: _model_file(
            STATIC_EVIDENCE_GATE3_CLOSEOUT_PATH,
            canonical_articulation_v2_static_gate3_closeout_bytes(
                plan,
                intake,
                generated_identities,
            ),
        ),
        intake.contract_uri: bundle.adoption.contract_file,
        STATIC_EVIDENCE_AUTHORING_RESULT_PATH: authoring.authoring_result,
        generated_file.path: generated_file,
        "receipts/contract.json": _model_file(
            "receipts/contract.json",
            canonical_articulation_v2_static_receipt_bytes(bundle.adoption),
        ),
        "receipts/authoring.json": _model_file(
            "receipts/authoring.json",
            canonical_articulation_v2_static_receipt_bytes(bundle.authoring),
        ),
        "receipts/readback.json": _model_file(
            "receipts/readback.json",
            canonical_articulation_v2_static_receipt_bytes(bundle.readback),
        ),
        "claims/gate3a.json": _model_file(
            "claims/gate3a.json",
            canonical_articulation_v2_static_receipt_bytes(bundle.gate3a),
        ),
        "claims/gate3b.json": _model_file(
            "claims/gate3b.json",
            canonical_articulation_v2_static_receipt_bytes(bundle.gate3b),
        ),
        bundle.gate3a.raw_report.path: bundle.gate3a.raw_report,
        bundle.gate3b.raw_report.path: bundle.gate3b.raw_report,
        bundle.gate3a.stdout_log.path: bundle.gate3a.stdout_log,
        bundle.gate3a.stderr_log.path: bundle.gate3a.stderr_log,
        bundle.gate3b.stdout_log.path: bundle.gate3b.stdout_log,
        bundle.gate3b.stderr_log.path: bundle.gate3b.stderr_log,
        STATIC_EVIDENCE_GATE3B_SUPPORT_PATH: support_evidence,
        STATIC_EVIDENCE_RESULT_BUNDLE_PATH: _model_file(
            STATIC_EVIDENCE_RESULT_BUNDLE_PATH,
            canonical_articulation_v2_static_result_bundle_bytes(bundle),
        ),
    }
    return files


def _model_file(path: str, payload: bytes) -> StaticReceiptFileV1:
    return StaticReceiptFileV1(
        path=path,
        size_bytes=len(payload),
        sha256=hashlib.sha256(payload).hexdigest(),
    )


def _evidence_binding(
    plan: ArticulationV2StaticRunPlanV1,
    intake: ArticulationV2StaticIntakeV1,
) -> ArticulationV2StaticEvidenceBindingV1:
    return ArticulationV2StaticEvidenceBindingV1(
        run_plan_sha256=articulation_v2_static_run_plan_sha256(plan),
        intake_sha256=articulation_v2_static_intake_sha256(intake),
        run=plan.run,
    )


def _require_generated_file_matches_identities(
    generated_file: StaticReceiptFileV1,
    identities: ArticulationV2StaticGeneratedArtifactIdentitiesV1,
) -> None:
    if generated_file.size_bytes <= 0:
        raise ValueError("generated artifact must retain nonempty bytes")
    if (
        generated_file.path != identities.authorer.uri
        or generated_file.sha256 != identities.authorer.root_sha256
    ):
        raise ValueError("generated file differs from dual URI/root identities")


def _require_sha256(value: str, label: str) -> str:
    if _SHA256_RE.fullmatch(value) is None:
        raise ValueError(f"{label} must be a lowercase SHA-256")
    return value


__all__ = [
    "ARTICULATION_V2_STATIC_ADOPTION_SCHEMA_VERSION",
    "ARTICULATION_V2_STATIC_AUTHORING_SCHEMA_VERSION",
    "ARTICULATION_V2_STATIC_COMPLETION_SCHEMA_VERSION",
    "ARTICULATION_V2_STATIC_GATE3_CLAIM_SCHEMA_VERSION",
    "ARTICULATION_V2_STATIC_GATE3_CLOSEOUT_SCHEMA_VERSION",
    "ARTICULATION_V2_STATIC_GATE3_FAILURE_SCHEMA_VERSION",
    "ARTICULATION_V2_STATIC_READBACK_SCHEMA_VERSION",
    "ARTICULATION_V2_STATIC_RESULT_BUNDLE_SCHEMA_VERSION",
    "ArticulationV2StaticAdoptionReceiptV1",
    "ArticulationV2StaticAuthoringReceiptV1",
    "ArticulationV2StaticComparisonChecksV1",
    "ArticulationV2StaticCompletionReceiptV1",
    "ArticulationV2StaticEvidenceBindingV1",
    "ArticulationV2StaticGate3ClaimV1",
    "ArticulationV2StaticGate3FailureReceiptV1",
    "ArticulationV2StaticReadbackReceiptV1",
    "ArticulationV2StaticReceipt",
    "ArticulationV2StaticReceiptStageV1",
    "ArticulationV2StaticResultBundleV1",
    "ReceiptStatus",
    "StaticReceiptFileV1",
    "articulation_v2_static_comparison_checks",
    "articulation_v2_static_completion_sha256",
    "articulation_v2_static_receipt_sha256",
    "canonical_articulation_v2_static_completion_bytes",
    "canonical_articulation_v2_static_gate3_closeout_bytes",
    "canonical_articulation_v2_static_gate3_failure_bytes",
    "canonical_articulation_v2_static_receipt_bytes",
    "canonical_articulation_v2_static_result_bundle_bytes",
    "validate_articulation_v2_static_completion_receipt",
    "validate_articulation_v2_static_result_bundle",
]
