# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""Deterministic, non-executing run-plan contracts for Joint 0.6.

The plan selects one exact #1012 admission and its admitted #1025 selector
lineage. It names a provider-neutral source request, reviewed command
identities, one fresh output locator, and the complete evidence-path allowlist.
Generated bytes and generated hashes do not exist at this boundary.
"""

from __future__ import annotations

import hashlib
import json
import re
from pathlib import PurePosixPath
from typing import Any, Literal

from pydantic import (
    BaseModel,
    ConfigDict,
    TypeAdapter,
    field_validator,
    model_validator,
)

from joint_agent.articulation_v2_static_artifact_identity import (
    ArticulationV2StaticGeneratedOutputLocatorV1,
    ArticulationV2StaticUsdRepresentation,
)
from joint_agent.articulation_v2_static_evidence_contracts import (
    ArticulationV2StaticEvidencePathAllowlistV1,
)
from joint_agent.articulation_v2_static_execution_command import (
    ArticulationV2StaticCommandV1,
)
from joint_agent.articulation_v2_static_semantics import (
    ArticulationV2StaticCapabilityId,
    ArticulationV2StaticDependencyBundleV3,
    ArticulationV2StaticSelectorAuthoringReferenceV1,
    ArticulationV2StaticUsdArtifactAuthorityV1,
)
from joint_agent.capability_manifest import (
    CapabilityManifestError,
    LoadedCapabilityManifest,
    StaticQualificationControlledDistanceSelectorAdmissionV2,
    StaticQualificationSelectorAdmissionV1,
    StaticQualificationStageAdmissionV1,
    require_static_selector_admission,
    require_static_stage_admission,
)
from joint_agent.static_qualification_contracts import (
    ARTICULATION_V2_STATIC_STAGE_VALIDATION_CONTRACTS,
    StaticQualificationValidationStageName,
)

ARTICULATION_V2_STATIC_RUN_PLAN_SCHEMA_VERSION: Literal[
    "joint-agent-articulation-v2-static-run-plan-v1"
] = "joint-agent-articulation-v2-static-run-plan-v1"
ARTICULATION_V2_STATIC_SELECTED_SOURCE_SCHEMA_VERSION: Literal[
    "joint-agent-articulation-v2-static-selected-source-v1"
] = "joint-agent-articulation-v2-static-selected-source-v1"
ARTICULATION_V2_STATIC_SELECTED_SOURCE_MAX_BYTES: Literal[536870912] = 536870912
ARTICULATION_V2_STATIC_CONTROLLED_DISTANCE_RUN_PLAN_SCHEMA_VERSION: Literal[
    "joint-agent-articulation-v2-static-run-plan-v2"
] = "joint-agent-articulation-v2-static-run-plan-v2"
ARTICULATION_V2_STATIC_CONTROLLED_DISTANCE_RUN_IDENTITY_SCHEMA_VERSION: Literal[
    "joint-agent-articulation-v2-static-run-identity-v2"
] = "joint-agent-articulation-v2-static-run-identity-v2"
ARTICULATION_V2_STATIC_CONTROLLED_DISTANCE_SELECTED_SOURCE_SCHEMA_VERSION: Literal[
    "joint-agent-articulation-v2-static-selected-source-v2"
] = "joint-agent-articulation-v2-static-selected-source-v2"
ARTICULATION_V2_STATIC_CONTROLLED_DISTANCE_REPRESENTATION: Literal[
    "prismatic_axial_interval_drive_body1_to_body0_v2"
] = "prismatic_axial_interval_drive_body1_to_body0_v2"

_SHA256_RE = re.compile(r"^[0-9a-f]{64}$")
_VERSION_RE = re.compile(r"^[0-9]+\.[0-9]+\.[0-9]+(?:-[a-z0-9.-]+)?$")
_RUN_ID_RE = re.compile(r"^[a-zA-Z0-9][a-zA-Z0-9._-]{0,127}$")
_RAW_USD_EXTENSIONS = frozenset({".usd", ".usda", ".usdc"})


class _RunPlanModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        frozen=True,
        strict=True,
        revalidate_instances="always",
    )


class ArticulationV2StaticSelectedSourceV1(_RunPlanModel):
    """Exact provider-neutral request for one admitted selector reference."""

    schema_version: Literal["joint-agent-articulation-v2-static-selected-source-v1"]
    locator: str
    representation: ArticulationV2StaticUsdRepresentation
    root_sha256: str
    max_bytes: Literal[536870912]
    gate3_dependency_bundle: ArticulationV2StaticDependencyBundleV3
    selector_lineage: ArticulationV2StaticSelectorAuthoringReferenceV1

    @field_validator("locator")
    @classmethod
    def _exact_locator(cls, value: str) -> str:
        if not value or value.strip() != value or "\x00" in value:
            raise ValueError("selected source locator must be exact and nonblank")
        return value

    @field_validator("root_sha256")
    @classmethod
    def _lowercase_sha256(cls, value: str) -> str:
        if _SHA256_RE.fullmatch(value) is None:
            raise ValueError("selected source root must be a lowercase SHA-256")
        return value

    @model_validator(mode="after")
    def _request_is_admitted_lineage(
        self,
    ) -> ArticulationV2StaticSelectedSourceV1:
        admitted = (
            self.selector_lineage.raw_reference
            if self.representation == "raw_usd"
            else self.selector_lineage.package_reference
        )
        if self.locator != admitted.path or self.root_sha256 != admitted.sha256:
            raise ValueError("selected source differs from admitted selector lineage")
        if self.gate3_dependency_bundle != admitted.dependency_bundle:
            raise ValueError("selected source differs from admitted Gate 3 v3 closure")
        suffix = PurePosixPath(self.locator).suffix.lower()
        if self.representation == "raw_usd" and suffix not in _RAW_USD_EXTENSIONS:
            raise ValueError("raw_usd source must name .usd, .usda, or .usdc")
        if self.representation == "usdz" and suffix != ".usdz":
            raise ValueError("usdz source must name a .usdz package")
        return self


class ArticulationV2StaticRunIdentityV1(_RunPlanModel):
    """Admission, typed selector lineage, and selected source for one run."""

    run_id: str
    capability_manifest_sha256: str
    row_admission_sha256: str
    capability_id: ArticulationV2StaticCapabilityId
    selector: StaticQualificationSelectorAdmissionV1
    selected_source: ArticulationV2StaticSelectedSourceV1

    @field_validator("run_id")
    @classmethod
    def _exact_run_id(cls, value: str) -> str:
        if _RUN_ID_RE.fullmatch(value) is None:
            raise ValueError("run_id must use canonical run identifier syntax")
        return value

    @field_validator("capability_manifest_sha256", "row_admission_sha256")
    @classmethod
    def _lowercase_sha256(cls, value: str, info: Any) -> str:
        if _SHA256_RE.fullmatch(value) is None:
            raise ValueError(f"{info.field_name} must be a lowercase SHA-256")
        return value

    @model_validator(mode="after")
    def _selector_and_source_are_exact(self) -> ArticulationV2StaticRunIdentityV1:
        semantics = self.selector.expected_joint_semantics
        if semantics.capability_id != self.capability_id:
            raise ValueError("run capability differs from typed selector semantics")
        if self.selected_source.selector_lineage != self.selector.authoring_reference:
            raise ValueError("selected source lineage differs from admitted selector")
        return self


class ArticulationV2StaticStagePlanV1(_RunPlanModel):
    """One atomic admission plus the reviewed command that will consume it."""

    stage: StaticQualificationValidationStageName
    admission: StaticQualificationStageAdmissionV1
    command: ArticulationV2StaticCommandV1

    @model_validator(mode="after")
    def _stage_contract_and_command_agree(self) -> ArticulationV2StaticStagePlanV1:
        if (
            self.admission.validation_contract
            != (ARTICULATION_V2_STATIC_STAGE_VALIDATION_CONTRACTS[self.stage])
        ):
            raise ValueError(f"{self.stage} plan carries a stale validation contract")
        if self.command.stage != self.stage:
            raise ValueError(f"{self.stage} plan carries a command for another stage")
        if self.command.profile_id != self.admission.profile_id:
            raise ValueError(f"{self.stage} command profile differs from admission")
        if self.command.result_id != self.admission.result_id:
            raise ValueError(f"{self.stage} command result differs from admission")
        return self


class ArticulationV2StaticStagePlansV1(_RunPlanModel):
    contract: ArticulationV2StaticStagePlanV1
    authoring: ArticulationV2StaticStagePlanV1
    readback: ArticulationV2StaticStagePlanV1
    gate3a: ArticulationV2StaticStagePlanV1
    gate3b: ArticulationV2StaticStagePlanV1

    @model_validator(mode="after")
    def _field_names_match_stages(self) -> ArticulationV2StaticStagePlansV1:
        for stage in ARTICULATION_V2_STATIC_STAGE_VALIDATION_CONTRACTS:
            if getattr(self, stage).stage != stage:
                raise ValueError(f"{stage} field must carry stage={stage!r}")
        return self

    def ordered(self) -> tuple[ArticulationV2StaticStagePlanV1, ...]:
        return (
            self.contract,
            self.authoring,
            self.readback,
            self.gate3a,
            self.gate3b,
        )


class ArticulationV2StaticRunPlanV1(_RunPlanModel):
    """One exact fixed/distance run consumed by later implementation packages."""

    schema_version: Literal["joint-agent-articulation-v2-static-run-plan-v1"]
    plan_version: str
    run: ArticulationV2StaticRunIdentityV1
    output: ArticulationV2StaticGeneratedOutputLocatorV1
    evidence_paths: ArticulationV2StaticEvidencePathAllowlistV1
    stages: ArticulationV2StaticStagePlansV1

    @field_validator("plan_version")
    @classmethod
    def _semantic_plan_version(cls, value: str) -> str:
        if _VERSION_RE.fullmatch(value) is None:
            raise ValueError("plan_version must be a canonical semantic version")
        return value

    @model_validator(mode="after")
    def _one_run_and_atomic_results(self) -> ArticulationV2StaticRunPlanV1:
        if self.output.run_id != self.run.run_id:
            raise ValueError("output locator differs from run identity")
        if self.evidence_paths.generated_output != self.output.output_key:
            raise ValueError("evidence allowlist differs from output locator")
        if self.evidence_paths.constraint_kind != self.run.selector.constraint_kind:
            raise ValueError("evidence allowlist differs from selected constraint")
        result_ids = tuple(stage.admission.result_id for stage in self.stages.ordered())
        if len(result_ids) != len(set(result_ids)):
            raise ValueError("each static stage requires a distinct result identity")
        return self


class ArticulationV2StaticControlledDistanceSelectedSourceV2(_RunPlanModel):
    """Exact admitted controlled-distance source-contract request."""

    schema_version: Literal["joint-agent-articulation-v2-static-selected-source-v2"]
    representation: Literal["prismatic_axial_interval_drive_body1_to_body0_v2"]
    locator: str
    root_sha256: str
    max_bytes: Literal[536870912]
    gate3_dependency_bundle: ArticulationV2StaticDependencyBundleV3
    source_authority: ArticulationV2StaticUsdArtifactAuthorityV1

    @field_validator("locator")
    @classmethod
    def _exact_locator(cls, value: str) -> str:
        if not value or value.strip() != value or "\x00" in value:
            raise ValueError("selected controlled-distance source must be exact")
        if PurePosixPath(value).suffix.lower() != ".usda":
            raise ValueError("controlled-distance v2 source must be exact USDA")
        return value

    @field_validator("root_sha256")
    @classmethod
    def _lowercase_sha256(cls, value: str) -> str:
        if _SHA256_RE.fullmatch(value) is None:
            raise ValueError("selected source root must be a lowercase SHA-256")
        return value

    @model_validator(mode="after")
    def _exact_authority(
        self,
    ) -> ArticulationV2StaticControlledDistanceSelectedSourceV2:
        if (
            self.locator != self.source_authority.path
            or self.root_sha256 != self.source_authority.sha256
            or self.gate3_dependency_bundle != self.source_authority.dependency_bundle
        ):
            raise ValueError("selected source differs from admitted v2 authority")
        return self


class ArticulationV2StaticControlledDistanceRunIdentityV2(_RunPlanModel):
    """Discriminated v2 admission and selected source for one run."""

    schema_version: Literal["joint-agent-articulation-v2-static-run-identity-v2"]
    run_id: str
    capability_manifest_sha256: str
    row_admission_sha256: str
    capability_id: Literal["distance.bounded_two_body_constraint"]
    selector: StaticQualificationControlledDistanceSelectorAdmissionV2
    selected_source: ArticulationV2StaticControlledDistanceSelectedSourceV2

    @field_validator("run_id")
    @classmethod
    def _exact_run_id(cls, value: str) -> str:
        if _RUN_ID_RE.fullmatch(value) is None:
            raise ValueError("run_id must use canonical run identifier syntax")
        return value

    @field_validator("capability_manifest_sha256", "row_admission_sha256")
    @classmethod
    def _lowercase_sha256(cls, value: str, info: Any) -> str:
        if _SHA256_RE.fullmatch(value) is None:
            raise ValueError(f"{info.field_name} must be a lowercase SHA-256")
        return value

    @model_validator(mode="after")
    def _exact_selector_source(
        self,
    ) -> ArticulationV2StaticControlledDistanceRunIdentityV2:
        semantics = self.selector.expected_joint_semantics
        if (
            semantics.capability_id != self.capability_id
            or self.selected_source.source_authority != semantics.source_contract
            or self.selected_source.representation
            != semantics.controlled_distance_contract.representation
        ):
            raise ValueError("run identity mixes controlled-distance v1/v2 authority")
        return self


class ArticulationV2StaticControlledDistanceRunPlanV2(_RunPlanModel):
    """Sibling run plan for the exact controlled-distance v2 representation."""

    schema_version: Literal["joint-agent-articulation-v2-static-run-plan-v2"]
    representation: Literal["prismatic_axial_interval_drive_body1_to_body0_v2"]
    plan_version: str
    run: ArticulationV2StaticControlledDistanceRunIdentityV2
    output: ArticulationV2StaticGeneratedOutputLocatorV1
    evidence_paths: ArticulationV2StaticEvidencePathAllowlistV1
    stages: ArticulationV2StaticStagePlansV1

    @field_validator("plan_version")
    @classmethod
    def _semantic_plan_version(cls, value: str) -> str:
        if _VERSION_RE.fullmatch(value) is None:
            raise ValueError("plan_version must be a canonical semantic version")
        return value

    @model_validator(mode="after")
    def _exact_v2_run(
        self,
    ) -> ArticulationV2StaticControlledDistanceRunPlanV2:
        if (
            self.representation != self.run.selected_source.representation
            or self.output.run_id != self.run.run_id
            or self.evidence_paths.generated_output != self.output.output_key
            or self.evidence_paths.constraint_kind != "distance"
        ):
            raise ValueError("controlled-distance v2 plan carries mixed run roles")
        result_ids = tuple(stage.admission.result_id for stage in self.stages.ordered())
        if len(result_ids) != len(set(result_ids)):
            raise ValueError("each static stage requires a distinct result identity")
        return self


_RUN_PLAN_ADAPTER = TypeAdapter(ArticulationV2StaticRunPlanV1)
_CONTROLLED_DISTANCE_RUN_PLAN_ADAPTER = TypeAdapter(
    ArticulationV2StaticControlledDistanceRunPlanV2
)


def canonical_articulation_v2_static_run_plan_bytes(
    plan: ArticulationV2StaticRunPlanV1,
) -> bytes:
    """Return the only accepted canonical JSON encoding for a 0.6 plan."""

    if type(plan) is not ArticulationV2StaticRunPlanV1:
        raise TypeError("plan must be an exact ArticulationV2StaticRunPlanV1")
    encoded = json.dumps(
        _RUN_PLAN_ADAPTER.dump_python(plan, mode="json"),
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
        allow_nan=False,
    ).encode("utf-8")
    validated = _RUN_PLAN_ADAPTER.validate_json(encoded, strict=True)
    return json.dumps(
        _RUN_PLAN_ADAPTER.dump_python(validated, mode="json"),
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
        allow_nan=False,
    ).encode("utf-8")


def articulation_v2_static_run_plan_sha256(
    plan: ArticulationV2StaticRunPlanV1,
) -> str:
    return hashlib.sha256(
        canonical_articulation_v2_static_run_plan_bytes(plan)
    ).hexdigest()


def canonical_articulation_v2_static_controlled_distance_run_plan_bytes(
    plan: ArticulationV2StaticControlledDistanceRunPlanV2,
) -> bytes:
    if type(plan) is not ArticulationV2StaticControlledDistanceRunPlanV2:
        raise TypeError("plan must be an exact controlled-distance v2 run plan")
    encoded = json.dumps(
        _CONTROLLED_DISTANCE_RUN_PLAN_ADAPTER.dump_python(plan, mode="json"),
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
        allow_nan=False,
    ).encode("utf-8")
    validated = _CONTROLLED_DISTANCE_RUN_PLAN_ADAPTER.validate_json(
        encoded, strict=True
    )
    return json.dumps(
        _CONTROLLED_DISTANCE_RUN_PLAN_ADAPTER.dump_python(validated, mode="json"),
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
        allow_nan=False,
    ).encode("utf-8")


def articulation_v2_static_controlled_distance_run_plan_sha256(
    plan: ArticulationV2StaticControlledDistanceRunPlanV2,
) -> str:
    return hashlib.sha256(
        canonical_articulation_v2_static_controlled_distance_run_plan_bytes(plan)
    ).hexdigest()


def validate_articulation_v2_static_run_plan(
    loaded: LoadedCapabilityManifest,
    plan: ArticulationV2StaticRunPlanV1,
) -> None:
    """Validate a plan against already-loaded #1012 authority without I/O."""

    plan = _revalidate_articulation_v2_static_run_plan(plan)
    if not isinstance(loaded, LoadedCapabilityManifest):
        raise CapabilityManifestError(
            "articulation-v2 static plan authority must be a loaded manifest"
        )
    run = plan.run
    if run.capability_manifest_sha256 != loaded.sha256:
        raise CapabilityManifestError(
            "articulation-v2 static plan uses a stale capability manifest"
        )
    row = next(
        (
            candidate
            for candidate in loaded.manifest.capabilities
            if candidate.capability_id == run.capability_id
        ),
        None,
    )
    if row is None or run.row_admission_sha256 != row.admission_sha256:
        raise CapabilityManifestError(
            "articulation-v2 static plan row admission identity does not match"
        )
    require_static_selector_admission(
        loaded,
        capability_id=run.capability_id,
        admission=run.selector,
    )
    if run.selected_source.selector_lineage != run.selector.authoring_reference:
        raise CapabilityManifestError(
            "articulation-v2 static plan uses self-asserted selector lineage"
        )
    for stage in plan.stages.ordered():
        require_static_stage_admission(
            loaded,
            capability_id=run.capability_id,
            stage=stage.stage,
            admission=stage.admission,
        )


def validate_articulation_v2_static_controlled_distance_run_plan(
    loaded: LoadedCapabilityManifest,
    plan: ArticulationV2StaticControlledDistanceRunPlanV2,
) -> None:
    """Validate one v2 plan against already-loaded manifest authority."""

    plan = _revalidate_articulation_v2_static_controlled_distance_run_plan(plan)
    if not isinstance(loaded, LoadedCapabilityManifest):
        raise CapabilityManifestError("v2 plan authority must be a loaded manifest")
    run = plan.run
    if run.capability_manifest_sha256 != loaded.sha256:
        raise CapabilityManifestError("controlled-distance v2 plan uses stale manifest")
    row = next(
        (
            candidate
            for candidate in loaded.manifest.capabilities
            if candidate.capability_id == run.capability_id
        ),
        None,
    )
    if row is None or run.row_admission_sha256 != row.admission_sha256:
        raise CapabilityManifestError("controlled-distance v2 row identity drifted")
    require_static_selector_admission(
        loaded,
        capability_id=run.capability_id,
        admission=run.selector,
    )
    for stage in plan.stages.ordered():
        require_static_stage_admission(
            loaded,
            capability_id=run.capability_id,
            stage=stage.stage,
            admission=stage.admission,
        )


def _revalidate_articulation_v2_static_run_plan(
    plan: ArticulationV2StaticRunPlanV1,
) -> ArticulationV2StaticRunPlanV1:
    if type(plan) is not ArticulationV2StaticRunPlanV1:
        raise CapabilityManifestError(
            "articulation-v2 static plan must use the exact 0.6 run-plan contract"
        )
    try:
        return _RUN_PLAN_ADAPTER.validate_json(
            canonical_articulation_v2_static_run_plan_bytes(plan),
            strict=True,
        )
    except (TypeError, ValueError) as exc:
        raise CapabilityManifestError(
            "articulation-v2 static plan fails strict invariant revalidation"
        ) from exc


def _revalidate_articulation_v2_static_controlled_distance_run_plan(
    plan: ArticulationV2StaticControlledDistanceRunPlanV2,
) -> ArticulationV2StaticControlledDistanceRunPlanV2:
    if type(plan) is not ArticulationV2StaticControlledDistanceRunPlanV2:
        raise CapabilityManifestError(
            "controlled-distance v2 plan must use the exact sibling contract"
        )
    try:
        return _CONTROLLED_DISTANCE_RUN_PLAN_ADAPTER.validate_json(
            canonical_articulation_v2_static_controlled_distance_run_plan_bytes(plan),
            strict=True,
        )
    except (TypeError, ValueError) as exc:
        raise CapabilityManifestError(
            "controlled-distance v2 plan fails strict invariant revalidation"
        ) from exc


__all__ = [
    "ARTICULATION_V2_STATIC_CONTROLLED_DISTANCE_REPRESENTATION",
    "ARTICULATION_V2_STATIC_CONTROLLED_DISTANCE_RUN_IDENTITY_SCHEMA_VERSION",
    "ARTICULATION_V2_STATIC_CONTROLLED_DISTANCE_RUN_PLAN_SCHEMA_VERSION",
    "ARTICULATION_V2_STATIC_CONTROLLED_DISTANCE_SELECTED_SOURCE_SCHEMA_VERSION",
    "ARTICULATION_V2_STATIC_RUN_PLAN_SCHEMA_VERSION",
    "ARTICULATION_V2_STATIC_SELECTED_SOURCE_MAX_BYTES",
    "ARTICULATION_V2_STATIC_SELECTED_SOURCE_SCHEMA_VERSION",
    "ArticulationV2StaticRunIdentityV1",
    "ArticulationV2StaticRunPlanV1",
    "ArticulationV2StaticControlledDistanceRunIdentityV2",
    "ArticulationV2StaticControlledDistanceRunPlanV2",
    "ArticulationV2StaticControlledDistanceSelectedSourceV2",
    "ArticulationV2StaticSelectedSourceV1",
    "ArticulationV2StaticStagePlanV1",
    "ArticulationV2StaticStagePlansV1",
    "articulation_v2_static_run_plan_sha256",
    "articulation_v2_static_controlled_distance_run_plan_sha256",
    "canonical_articulation_v2_static_run_plan_bytes",
    "canonical_articulation_v2_static_controlled_distance_run_plan_bytes",
    "validate_articulation_v2_static_run_plan",
    "validate_articulation_v2_static_controlled_distance_run_plan",
]
