# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""Inert generated-output identities for articulation-v2 static runs.

Run plans carry only a fresh locator. Generated digests enter the wire contract
only after bytes have been retained. The authorer's ``ArtifactIdentityV1`` and
the Gate 3 v3 dependency-manifest identity remain separate objects: their URI
and root bytes must agree, while neither dependency digest substitutes for the
other.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import stat
import tempfile
import zipfile
from collections.abc import Iterator
from contextlib import ExitStack, contextmanager
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator
from world_understanding.functions.physics.joint_rigger import ArtifactIdentityV1
from world_understanding.utils.artifacts import validated_artifact_relative_key
from world_understanding.utils.captured_artifacts import (
    CapturedArtifactError,
    CapturedOpaqueFile,
)

ARTICULATION_V2_STATIC_GENERATED_ARTIFACT_IDENTITY_SCHEMA_VERSION: Literal[
    "joint-agent-articulation-v2-static-generated-artifact-dependency-identity-v1"
] = "joint-agent-articulation-v2-static-generated-artifact-dependency-identity-v1"
ARTICULATION_V2_STATIC_GENERATED_ARTIFACT_IDENTITIES_SCHEMA_VERSION: Literal[
    "joint-agent-articulation-v2-static-generated-artifact-identities-v1"
] = "joint-agent-articulation-v2-static-generated-artifact-identities-v1"
ARTICULATION_V2_STATIC_ARTIFACT_DEPENDENCY_BUNDLE_SCHEMA_VERSION: Literal[
    "joint-agent-usd-artifact-dependency-bundle-v3"
] = "joint-agent-usd-artifact-dependency-bundle-v3"
ARTICULATION_V2_STATIC_OUTPUT_LOCATOR_SCHEMA_VERSION: Literal[
    "joint-agent-articulation-v2-static-output-locator-v1"
] = "joint-agent-articulation-v2-static-output-locator-v1"

type ArticulationV2StaticUsdRepresentation = Literal["raw_usd", "usdz"]

_RAW_USD_EXTENSIONS = frozenset({".usd", ".usda", ".usdc"})
_USD_EXTENSIONS = _RAW_USD_EXTENSIONS | {".usdz"}
_SHA256_RE = re.compile(r"^[0-9a-f]{64}$")
_RUN_ID_RE = re.compile(r"^[a-zA-Z0-9][a-zA-Z0-9._-]{0,127}$")


class ArticulationV2StaticArtifactIdentityError(RuntimeError):
    """Fail-closed retained-artifact identity error."""


@dataclass(frozen=True, slots=True)
class ArticulationV2StaticGate3DependencyEntryV1:
    """One immutable Gate 3 v3 dependency-manifest member."""

    kind: str
    path: str
    size: int
    sha256: str


@dataclass(frozen=True, slots=True)
class ArticulationV2StaticGate3DependencyManifestV1:
    """The retained, independently computed Gate 3 v3 manifest."""

    container: Literal["raw_usd", "usdz"]
    entries: tuple[ArticulationV2StaticGate3DependencyEntryV1, ...]
    sha256: str
    root_entry: str | None = None


class _ArtifactModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        frozen=True,
        strict=True,
        revalidate_instances="always",
    )


class ArticulationV2StaticGeneratedOutputLocatorV1(_ArtifactModel):
    """Fresh output destination known before generated bytes exist."""

    schema_version: Literal["joint-agent-articulation-v2-static-output-locator-v1"]
    run_id: str
    output_key: str
    output_uri: str

    @field_validator("run_id")
    @classmethod
    def _exact_run_id(cls, value: str) -> str:
        if _RUN_ID_RE.fullmatch(value) is None:
            raise ValueError("output locator run_id must use canonical syntax")
        return value

    @field_validator("output_key")
    @classmethod
    def _canonical_output_key(cls, value: str) -> str:
        canonical = _canonical_relative_usd_path(value, "output_key")
        if not canonical.startswith("output/"):
            raise ValueError("output_key must use the output/ namespace")
        return canonical

    @model_validator(mode="after")
    def _run_scoped_uri(self) -> ArticulationV2StaticGeneratedOutputLocatorV1:
        expected = f"joint-run://{self.run_id}/{self.output_key}"
        if self.output_uri != expected:
            raise ValueError("output_uri must be the canonical run-scoped locator")
        return self


class ArticulationV2StaticGeneratedArtifactDependencyIdentityV1(_ArtifactModel):
    """Gate 3 v3 identity for retained generated USD or USDZ bytes.

    ``entry_count`` always counts the entries in the admitted v3 dependency
    manifest. Raw USD is admitted here only when it is a self-contained
    one-entry artifact because this contract retains one generated output path;
    USDZ may contain one or more package entries behind that retained package.
    """

    schema_version: Literal[
        "joint-agent-articulation-v2-static-generated-artifact-dependency-identity-v1"
    ]
    uri: str
    representation: ArticulationV2StaticUsdRepresentation
    root_sha256: str
    dependency_bundle_schema_version: Literal[
        "joint-agent-usd-artifact-dependency-bundle-v3"
    ]
    dependency_bundle_sha256: str
    dependency_bundle_entry_count: int = Field(ge=1)

    @field_validator("uri")
    @classmethod
    def _canonical_output_uri(cls, value: str) -> str:
        canonical = _canonical_relative_usd_path(value, "generated artifact uri")
        if not canonical.startswith("output/"):
            raise ValueError("generated artifact uri must use the output/ namespace")
        return canonical

    @field_validator("root_sha256", "dependency_bundle_sha256")
    @classmethod
    def _lowercase_sha256(cls, value: str, info: Any) -> str:
        if _SHA256_RE.fullmatch(value) is None:
            raise ValueError(f"{info.field_name} must be a lowercase SHA-256")
        return value

    @model_validator(mode="after")
    def _representation_matches_uri(
        self,
    ) -> ArticulationV2StaticGeneratedArtifactDependencyIdentityV1:
        _require_representation_matches_path(self.representation, self.uri)
        if self.representation == "raw_usd" and self.dependency_bundle_entry_count != 1:
            raise ValueError(
                "raw_usd retained evidence requires one self-contained manifest entry"
            )
        return self


class ArticulationV2StaticGeneratedArtifactIdentitiesV1(_ArtifactModel):
    """Dual identity contract established from the same retained root bytes."""

    schema_version: Literal[
        "joint-agent-articulation-v2-static-generated-artifact-identities-v1"
    ]
    representation: ArticulationV2StaticUsdRepresentation
    authorer: ArtifactIdentityV1
    gate3: ArticulationV2StaticGeneratedArtifactDependencyIdentityV1

    @field_validator("authorer", mode="before")
    @classmethod
    def _strict_authorer_identity(cls, value: object) -> ArtifactIdentityV1:
        if type(value) is ArtifactIdentityV1:
            payload = value.model_dump(mode="json")
        elif type(value) is dict:
            payload = value
        else:
            raise ValueError("authorer identity must be an exact ArtifactIdentityV1")
        try:
            encoded = json.dumps(
                payload,
                sort_keys=True,
                separators=(",", ":"),
                ensure_ascii=False,
                allow_nan=False,
            )
        except (TypeError, ValueError) as exc:
            raise ValueError("authorer identity must be JSON-compatible") from exc
        return ArtifactIdentityV1.model_validate_json(encoded, strict=True)

    @model_validator(mode="after")
    def _same_retained_root_distinct_dependency_domains(
        self,
    ) -> ArticulationV2StaticGeneratedArtifactIdentitiesV1:
        if type(self.authorer) is not ArtifactIdentityV1:
            raise ValueError("authorer identity must be an exact ArtifactIdentityV1")
        if self.authorer.dependency_bundle_sha256 is None:
            raise ValueError("authorer identity requires its own dependency digest")
        if (
            self.authorer.dependency_bundle_sha256
            == self.gate3.dependency_bundle_sha256
        ):
            raise ValueError(
                "authorer and Gate 3 dependency digests must remain distinct"
            )
        if (
            self.authorer.uri != self.gate3.uri
            or self.authorer.root_sha256 != self.gate3.root_sha256
        ):
            raise ValueError("authorer and Gate 3 URI/root identities differ")
        if self.representation != self.gate3.representation:
            raise ValueError("generated representation differs from Gate 3 identity")
        _require_representation_matches_path(self.representation, self.authorer.uri)
        return self


def _canonical_relative_usd_path(value: str, label: str) -> str:
    try:
        canonical: str = validated_artifact_relative_key(value)
    except ValueError as exc:
        raise ValueError(f"{label} must be a canonical relative POSIX path") from exc
    if PurePosixPath(canonical).suffix.lower() not in _USD_EXTENSIONS:
        raise ValueError(f"{label} must name USD or USDZ output")
    return canonical


def _require_representation_matches_path(
    representation: ArticulationV2StaticUsdRepresentation,
    path: str,
) -> None:
    suffix = PurePosixPath(path).suffix.lower()
    if representation == "raw_usd" and suffix not in _RAW_USD_EXTENSIONS:
        raise ValueError("raw_usd representation requires .usd, .usda, or .usdc")
    if representation == "usdz" and suffix != ".usdz":
        raise ValueError("usdz representation requires a .usdz path")


def gate3_v3_dependency_manifest_from_capture(
    capture: CapturedOpaqueFile,
    *,
    representation: ArticulationV2StaticUsdRepresentation,
) -> ArticulationV2StaticGate3DependencyManifestV1:
    """Compute the Gate 3 v3 inventory from retained, not live, bytes.

    The static run contract admits a single complete raw layer or a complete
    USDZ package.  The temporary materialization here is private, mode 0700,
    and discarded before the captured descriptor is released.  It exists only
    because OpenUSD's closure check requires a pathname; no caller-visible
    source projection is created.
    """

    if type(capture) is not CapturedOpaqueFile:
        raise TypeError("capture must be an exact CapturedOpaqueFile")
    suffix = PurePosixPath(capture.uri).suffix.lower()
    try:
        _require_representation_matches_path(representation, capture.uri)
    except ValueError as exc:
        raise ArticulationV2StaticArtifactIdentityError(
            "retained capture URI does not match its USD representation"
        ) from exc
    try:
        capture.require_intact()
        with _private_capture_path(capture, suffix=suffix) as retained_path:
            _require_self_contained_usd(retained_path, representation=representation)
            if representation == "raw_usd":
                manifest = _raw_usd_v3_manifest(capture)
            else:
                manifest = _usdz_v3_manifest(retained_path)
        capture.require_intact()
    except CapturedArtifactError as exc:
        raise ArticulationV2StaticArtifactIdentityError(
            "retained capture integrity check failed"
        ) from exc
    return manifest


def identify_articulation_v2_static_generated_artifact(
    path: str | os.PathLike[str],
    *,
    output: ArticulationV2StaticGeneratedOutputLocatorV1,
) -> ArticulationV2StaticGeneratedArtifactIdentitiesV1:
    """Return identities when the retained bytes need not be published.

    Callers that will copy the output into evidence must instead use
    :func:`capture_articulation_v2_static_generated_artifact` and write its
    still-open capture.  That prevents reopening a mutable generated path
    after the two identity domains have been established.
    """

    with capture_articulation_v2_static_generated_artifact(
        path,
        output=output,
    ) as (_capture, identities):
        return identities


@contextmanager
def capture_articulation_v2_static_generated_artifact(
    path: str | os.PathLike[str],
    *,
    output: ArticulationV2StaticGeneratedOutputLocatorV1,
) -> Iterator[
    tuple[CapturedOpaqueFile, ArticulationV2StaticGeneratedArtifactIdentitiesV1]
]:
    """Yield exact generated bytes together with their dual identities.

    The authorer identity is recomputed with the existing Joint Rigger
    ``ArtifactIdentityV1`` implementation.  Gate 3 uses its own v3 package
    manifest over the same captured root bytes.  The capture remains open only
    for this context, so an evidence publisher can copy the exact bytes that
    both identity domains describe without reopening ``path``.
    """

    if type(output) is not ArticulationV2StaticGeneratedOutputLocatorV1:
        raise TypeError("output must be an exact generated-output locator")
    try:
        output = ArticulationV2StaticGeneratedOutputLocatorV1.model_validate(
            output.model_dump(mode="json"),
            strict=True,
        )
    except (TypeError, ValueError) as exc:
        raise ArticulationV2StaticArtifactIdentityError(
            "generated output locator fails strict revalidation"
        ) from exc
    representation = _representation_for_output_key(output.output_key)
    try:
        _require_representation_matches_path(representation, os.fspath(path))
    except ValueError as exc:
        raise ArticulationV2StaticArtifactIdentityError(
            "generated output path does not match its output-key representation"
        ) from exc
    caller_exception = False
    try:
        with _capture_local_generated_output(path, uri=output.output_key) as capture:
            with _private_capture_path(
                capture,
                suffix=PurePosixPath(output.output_key).suffix.lower(),
            ) as retained_path:
                gate3_manifest = _gate3_v3_manifest_from_retained_path(
                    retained_path,
                    capture=capture,
                    representation=representation,
                )
                authorer = _authorer_identity_from_retained_path(
                    retained_path,
                    uri=output.output_key,
                )
            capture.require_intact()
            gate3 = ArticulationV2StaticGeneratedArtifactDependencyIdentityV1(
                schema_version=(
                    ARTICULATION_V2_STATIC_GENERATED_ARTIFACT_IDENTITY_SCHEMA_VERSION
                ),
                uri=output.output_key,
                representation=representation,
                root_sha256=capture.sha256,
                dependency_bundle_schema_version=(
                    ARTICULATION_V2_STATIC_ARTIFACT_DEPENDENCY_BUNDLE_SCHEMA_VERSION
                ),
                dependency_bundle_sha256=gate3_manifest.sha256,
                dependency_bundle_entry_count=len(gate3_manifest.entries),
            )
            identities = ArticulationV2StaticGeneratedArtifactIdentitiesV1(
                schema_version=(
                    ARTICULATION_V2_STATIC_GENERATED_ARTIFACT_IDENTITIES_SCHEMA_VERSION
                ),
                representation=representation,
                authorer=authorer,
                gate3=gate3,
            )
            caller_exception = True
            yield capture, identities
            caller_exception = False
    except CapturedArtifactError as exc:
        if caller_exception:
            raise
        raise ArticulationV2StaticArtifactIdentityError(
            "generated retained capture integrity check failed"
        ) from exc


@contextmanager
def _capture_local_generated_output(
    path: str | os.PathLike[str],
    *,
    uri: str,
) -> Iterator[CapturedOpaqueFile]:
    """Capture one generated regular file through no-follow parent dirfds.

    The live pathname is admission authority only until the retained capture has
    been sealed and revalidated.  Once yielded, consumers must use that capture
    rather than reopen the mutable pathname, so a later producer-side rename or
    replacement cannot turn an already-published exact evidence root into a
    retryable identity failure.
    """

    from world_understanding.utils.artifacts import (
        ArtifactPathError,
        open_confined_directory,
        open_confined_regular_file,
    )
    from world_understanding.utils.captured_artifacts import (
        OpaqueArtifactRequest,
        capture_streamed_opaque_file,
    )

    candidate = os.fspath(path)
    if not candidate or "\x00" in candidate:
        raise ArticulationV2StaticArtifactIdentityError(
            "generated output path must be nonblank and contain no null bytes"
        )
    parent, leaf = os.path.split(os.path.abspath(candidate))
    if not leaf or leaf in {".", ".."}:
        raise ArticulationV2StaticArtifactIdentityError(
            "generated output path must name one regular file"
        )
    stack = ExitStack()
    try:
        parent_descriptor = stack.enter_context(open_confined_directory(parent))
        stream, before = stack.enter_context(
            open_confined_regular_file(parent_descriptor, leaf)
        )
        if not stat.S_ISREG(before.st_mode):  # defensive helper contract
            raise ArticulationV2StaticArtifactIdentityError(
                "generated output is not a regular file"
            )
        digest = hashlib.sha256()
        while chunk := stream.read(1024 * 1024):
            digest.update(chunk)
        after = os.fstat(stream.fileno())
        if _file_state(before) != _file_state(after):
            raise ArticulationV2StaticArtifactIdentityError(
                "generated output changed while its bytes were captured"
            )
        _require_current_generated_output_state(
            parent_descriptor,
            leaf,
            expected=before,
            phase="captured",
        )
        stream.seek(0)
        request = OpaqueArtifactRequest(
            uri=uri,
            sha256=digest.hexdigest(),
            size_bytes=before.st_size,
            max_bytes=before.st_size,
        )
        capture = stack.enter_context(capture_streamed_opaque_file(stream, request))
        if _file_state(before) != _file_state(os.fstat(stream.fileno())):
            raise ArticulationV2StaticArtifactIdentityError(
                "generated output changed while its bytes were retained"
            )
        _require_current_generated_output_state(
            parent_descriptor,
            leaf,
            expected=before,
            phase="retained",
        )
        _require_current_generated_output_parent(
            parent,
            expected=(
                os.fstat(parent_descriptor).st_dev,
                os.fstat(parent_descriptor).st_ino,
            ),
        )
    except (ArtifactPathError, CapturedArtifactError, OSError, ValueError) as exc:
        stack.close()
        raise ArticulationV2StaticArtifactIdentityError(
            "generated output could not be traversed as a regular no-follow file"
        ) from exc
    except BaseException:
        stack.close()
        raise

    try:
        yield capture
    except BaseException:
        try:
            stack.close()
        except BaseException:
            pass
        raise
    else:
        stack.close()


@contextmanager
def _private_capture_path(
    capture: CapturedOpaqueFile,
    *,
    suffix: str,
) -> Iterator[Path]:
    """Write a captured descriptor to an owner-private, read-only file."""

    if not suffix.startswith(".") or suffix.lower() not in _USD_EXTENSIONS:
        raise ValueError("private captured artifact requires a USD or USDZ suffix")
    with tempfile.TemporaryDirectory(prefix="joint-agent-static-capture-") as root:
        destination = os.path.join(root, f"retained{suffix}")
        descriptor = os.open(
            destination,
            os.O_CREAT | os.O_EXCL | os.O_WRONLY | getattr(os, "O_CLOEXEC", 0),
            0o600,
        )
        digest = hashlib.sha256()
        total = 0
        try:
            for chunk in capture.iter_chunks():
                _write_all(descriptor, chunk)
                digest.update(chunk)
                total += len(chunk)
            if total != capture.size_bytes or digest.hexdigest() != capture.sha256:
                raise ArticulationV2StaticArtifactIdentityError(
                    "retained capture differs from its descriptor identity"
                )
            os.fsync(descriptor)
            os.fchmod(descriptor, 0o400)
        finally:
            os.close(descriptor)
        capture.require_intact()
        yield Path(destination)


def _gate3_v3_manifest_from_retained_path(
    path: Path,
    *,
    capture: CapturedOpaqueFile,
    representation: ArticulationV2StaticUsdRepresentation,
) -> ArticulationV2StaticGate3DependencyManifestV1:
    _require_self_contained_usd(path, representation=representation)
    if representation == "raw_usd":
        return _raw_usd_v3_manifest(capture)
    return _usdz_v3_manifest(path)


def _raw_usd_v3_manifest(
    capture: CapturedOpaqueFile,
) -> ArticulationV2StaticGate3DependencyManifestV1:
    entry = ArticulationV2StaticGate3DependencyEntryV1(
        kind="root_layer",
        path="<root>",
        size=capture.size_bytes,
        sha256=capture.sha256,
    )
    return _gate3_manifest(container="raw_usd", entries=(entry,))


def _usdz_v3_manifest(path: Path) -> ArticulationV2StaticGate3DependencyManifestV1:
    try:
        with zipfile.ZipFile(path) as archive:
            infos = archive.infolist()
            names = [info.filename for info in infos]
            if not infos:
                raise ArticulationV2StaticArtifactIdentityError("USDZ package is empty")
            if len(names) != len(set(names)):
                raise ArticulationV2StaticArtifactIdentityError(
                    "USDZ package contains duplicate entries"
                )
            root = infos[0]
            if root.is_dir() or PurePosixPath(root.filename).suffix.lower() not in (
                _RAW_USD_EXTENSIONS
            ):
                raise ArticulationV2StaticArtifactIdentityError(
                    "USDZ first entry must be a USD root layer"
                )
            entries: list[ArticulationV2StaticGate3DependencyEntryV1] = []
            for info in infos:
                _validate_usdz_entry(info)
                if info.is_dir():
                    entries.append(
                        ArticulationV2StaticGate3DependencyEntryV1(
                            kind="package_directory",
                            path=info.filename,
                            size=0,
                            sha256=hashlib.sha256(b"").hexdigest(),
                        )
                    )
                    continue
                digest = hashlib.sha256()
                with archive.open(info) as stream:
                    for chunk in iter(lambda: stream.read(1024 * 1024), b""):
                        digest.update(chunk)
                entries.append(
                    ArticulationV2StaticGate3DependencyEntryV1(
                        kind="package_entry",
                        path=info.filename,
                        size=info.file_size,
                        sha256=digest.hexdigest(),
                    )
                )
    except ArticulationV2StaticArtifactIdentityError:
        raise
    except (OSError, RuntimeError, zipfile.BadZipFile) as exc:
        raise ArticulationV2StaticArtifactIdentityError(
            "could not read retained USDZ package"
        ) from exc
    return _gate3_manifest(
        container="usdz",
        entries=tuple(sorted(entries, key=lambda entry: entry.path)),
        root_entry=root.filename,
    )


def _gate3_manifest(
    *,
    container: Literal["raw_usd", "usdz"],
    entries: tuple[ArticulationV2StaticGate3DependencyEntryV1, ...],
    root_entry: str | None = None,
) -> ArticulationV2StaticGate3DependencyManifestV1:
    document: dict[str, object] = {
        "schema_version": ARTICULATION_V2_STATIC_ARTIFACT_DEPENDENCY_BUNDLE_SCHEMA_VERSION,
        "container": container,
        "entries": [
            {
                "kind": entry.kind,
                "path": entry.path,
                "size": entry.size,
                "sha256": entry.sha256,
            }
            for entry in entries
        ],
    }
    if root_entry is not None:
        document["root_entry"] = root_entry
    encoded = json.dumps(
        document,
        ensure_ascii=True,
        separators=(",", ":"),
        sort_keys=True,
    ).encode("utf-8")
    return ArticulationV2StaticGate3DependencyManifestV1(
        container=container,
        entries=entries,
        sha256=hashlib.sha256(encoded).hexdigest(),
        root_entry=root_entry,
    )


def _validate_usdz_entry(info: zipfile.ZipInfo) -> None:
    name = info.filename
    pure_path = PurePosixPath(name)
    canonical_name = pure_path.as_posix() + ("/" if info.is_dir() else "")
    if (
        not name
        or "\\" in name
        or not pure_path.parts
        or pure_path.is_absolute()
        or ".." in pure_path.parts
        or name != canonical_name
    ):
        raise ArticulationV2StaticArtifactIdentityError(
            "USDZ package contains an unsafe entry path"
        )
    if info.flag_bits & 0x1:
        raise ArticulationV2StaticArtifactIdentityError(
            "USDZ package contains an encrypted entry"
        )
    if info.compress_type != zipfile.ZIP_STORED:
        raise ArticulationV2StaticArtifactIdentityError(
            "USDZ package contains a compressed entry"
        )
    mode = info.external_attr >> 16
    file_type = stat.S_IFMT(mode)
    if file_type == stat.S_IFLNK:
        raise ArticulationV2StaticArtifactIdentityError(
            "USDZ package contains a symbolic-link entry"
        )
    if info.is_dir():
        if info.file_size or info.compress_size:
            raise ArticulationV2StaticArtifactIdentityError(
                "USDZ package contains a nonempty directory entry"
            )
        if file_type not in {0, stat.S_IFDIR}:
            raise ArticulationV2StaticArtifactIdentityError(
                "USDZ package contains a special directory entry"
            )
    elif file_type not in {0, stat.S_IFREG}:
        raise ArticulationV2StaticArtifactIdentityError(
            "USDZ package contains a special file entry"
        )


def _require_self_contained_usd(
    path: Path,
    *,
    representation: ArticulationV2StaticUsdRepresentation,
) -> None:
    """Reject dependencies beyond the retained one-file/package boundary."""

    try:
        from pxr import Ar, UsdUtils

        layers, assets, unresolved = UsdUtils.ComputeAllDependencies(str(path))
    except Exception as exc:
        raise ArticulationV2StaticArtifactIdentityError(
            "could not enumerate the retained USD dependency closure"
        ) from exc
    if unresolved:
        raise ArticulationV2StaticArtifactIdentityError(
            "retained USD dependency closure contains unresolved locators"
        )
    expected = path.resolve()
    dependencies = [
        str(
            getattr(value, "resolvedPath", None)
            or getattr(value, "realPath", None)
            or value
        )
        for value in (*layers, *assets)
    ]
    if representation == "raw_usd":
        if not dependencies:
            raise ArticulationV2StaticArtifactIdentityError(
                "raw USD dependency enumeration omitted the root layer"
            )
        if any(not _same_local_path(item, expected) for item in dependencies):
            raise ArticulationV2StaticArtifactIdentityError(
                "raw USD output has a dependency outside its retained root"
            )
        return
    for identifier in dependencies:
        if Ar.IsPackageRelativePath(identifier):
            outer, _inner = Ar.SplitPackageRelativePathOuter(identifier)
            if not _same_local_path(outer, expected):
                raise ArticulationV2StaticArtifactIdentityError(
                    "USDZ output has a dependency outside its retained package"
                )
        elif not _same_local_path(identifier, expected):
            raise ArticulationV2StaticArtifactIdentityError(
                "USDZ output has a dependency outside its retained package"
            )


def _authorer_identity_from_retained_path(
    path: Path, *, uri: str
) -> ArtifactIdentityV1:
    from world_understanding.functions.physics.joint_rigger import identify_usd_artifact

    try:
        identity = identify_usd_artifact(path, uri=uri)
    except Exception as exc:
        raise ArticulationV2StaticArtifactIdentityError(
            "could not establish the authorer ArtifactIdentityV1"
        ) from exc
    if type(identity) is not ArtifactIdentityV1:
        raise ArticulationV2StaticArtifactIdentityError(
            "authorer identity implementation returned an unexpected model"
        )
    return identity


def _representation_for_output_key(
    output_key: str,
) -> ArticulationV2StaticUsdRepresentation:
    return "usdz" if output_key.lower().endswith(".usdz") else "raw_usd"


def _same_local_path(value: str, expected: Path) -> bool:
    try:
        return Path(value).resolve() == expected
    except (OSError, ValueError):
        return False


def _require_current_generated_output_state(
    parent_descriptor: int,
    leaf: str,
    *,
    expected: os.stat_result,
    phase: str,
) -> None:
    """Refuse a replacement of the generated path while its capture is live."""

    observed = os.stat(leaf, dir_fd=parent_descriptor, follow_symlinks=False)
    if not stat.S_ISREG(observed.st_mode) or _file_state(observed) != _file_state(
        expected
    ):
        raise ArticulationV2StaticArtifactIdentityError(
            f"generated output path changed while its bytes were {phase}"
        )


def _require_current_generated_output_parent(
    parent: str,
    *,
    expected: tuple[int, int],
) -> None:
    """Require the lexical parent to remain the descriptor-bound directory."""

    from world_understanding.utils.artifacts import (
        ArtifactPathError,
        open_confined_directory,
    )

    try:
        with open_confined_directory(parent) as descriptor:
            observed = os.fstat(descriptor)
    except (ArtifactPathError, OSError, ValueError) as exc:
        raise ArticulationV2StaticArtifactIdentityError(
            "generated output parent changed while its bytes were retained"
        ) from exc
    if (observed.st_dev, observed.st_ino) != expected:
        raise ArticulationV2StaticArtifactIdentityError(
            "generated output parent changed while its bytes were retained"
        )


def _file_state(metadata: os.stat_result) -> tuple[int, int, int, int, int, int, int]:
    return (
        metadata.st_dev,
        metadata.st_ino,
        metadata.st_mode,
        metadata.st_nlink,
        metadata.st_size,
        metadata.st_mtime_ns,
        metadata.st_ctime_ns,
    )


def _write_all(descriptor: int, payload: bytes) -> None:
    view = memoryview(payload)
    while view:
        written = os.write(descriptor, view)
        if written <= 0:  # pragma: no cover - regular-file invariant
            raise OSError("could not write retained artifact bytes")
        view = view[written:]


__all__ = [
    "ARTICULATION_V2_STATIC_ARTIFACT_DEPENDENCY_BUNDLE_SCHEMA_VERSION",
    "ARTICULATION_V2_STATIC_GENERATED_ARTIFACT_IDENTITIES_SCHEMA_VERSION",
    "ARTICULATION_V2_STATIC_GENERATED_ARTIFACT_IDENTITY_SCHEMA_VERSION",
    "ARTICULATION_V2_STATIC_OUTPUT_LOCATOR_SCHEMA_VERSION",
    "ArticulationV2StaticArtifactIdentityError",
    "ArticulationV2StaticGeneratedArtifactDependencyIdentityV1",
    "ArticulationV2StaticGeneratedArtifactIdentitiesV1",
    "ArticulationV2StaticGeneratedOutputLocatorV1",
    "ArticulationV2StaticGate3DependencyEntryV1",
    "ArticulationV2StaticGate3DependencyManifestV1",
    "ArticulationV2StaticUsdRepresentation",
    "capture_articulation_v2_static_generated_artifact",
    "gate3_v3_dependency_manifest_from_capture",
    "identify_articulation_v2_static_generated_artifact",
]
