# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""Strict terminal receipts for controlled-distance-v2 static runs.

These sibling models deliberately do not widen or reinterpret the frozen V1
receipt surface.  They bind the V2 representation, run-plan, intake, admitted
semantic contract, saved-stage readback, generated bytes, and terminal
inventory without performing I/O or execution.
"""

from __future__ import annotations

import hashlib
import json
import math
import struct
from typing import Any, Literal, TypeVar, cast

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    TypeAdapter,
    field_validator,
    model_validator,
)

from joint_agent.articulation_v2_static_artifact_identity import (
    ArticulationV2StaticGeneratedArtifactIdentitiesV1,
)
from joint_agent.articulation_v2_static_evidence_contracts import (
    STATIC_EVIDENCE_AUTHORING_RESULT_PATH,
    STATIC_EVIDENCE_GATE3_CLOSEOUT_PATH,
    STATIC_EVIDENCE_GATE3_FAILURE_RECEIPT_PATH,
    STATIC_EVIDENCE_GATE3B_SUPPORT_PATH,
    STATIC_EVIDENCE_INTAKE_PATH,
    STATIC_EVIDENCE_RESULT_BUNDLE_PATH,
    STATIC_EVIDENCE_RUN_PLAN_PATH,
    STATIC_EVIDENCE_TERMINAL_RECEIPT_PATH,
    ArticulationV2StaticEvidencePathAllowlistV1,
    articulation_v2_static_gate3a_failure_paths,
    articulation_v2_static_gate3b_failure_paths,
)
from joint_agent.articulation_v2_static_intake import (
    ARTICULATION_V2_STATIC_CONTROLLED_DISTANCE_REPRESENTATION,
    ArticulationV2StaticControlledDistanceIntakeV2,
    _revalidate_articulation_v2_static_controlled_distance_intake,
    articulation_v2_static_controlled_distance_intake_sha256,
    canonical_articulation_v2_static_controlled_distance_intake_bytes,
    validate_articulation_v2_static_controlled_distance_intake,
)
from joint_agent.articulation_v2_static_receipts import (
    ReceiptStatus,
    StaticReceiptFileV1,
)
from joint_agent.articulation_v2_static_run_plan import (
    ArticulationV2StaticControlledDistanceRunIdentityV2,
    ArticulationV2StaticControlledDistanceRunPlanV2,
    ArticulationV2StaticStagePlanV1,
    _revalidate_articulation_v2_static_controlled_distance_run_plan,
    articulation_v2_static_controlled_distance_run_plan_sha256,
    canonical_articulation_v2_static_controlled_distance_run_plan_bytes,
)
from joint_agent.articulation_v2_static_semantics import (
    ArticulationV2ControlledDistanceSelectorSemanticsV2,
    ControlledDistanceSelectorSemanticPreimageV2,
    _quaternion,
    _scaled_vector,
    articulation_v2_controlled_distance_selector_semantics_sha256,
)
from joint_agent.capability_manifest import (
    CapabilityManifestError,
    LoadedCapabilityManifest,
)
from joint_agent.functions.articulation_contract_v2_frames import (
    AttachmentFrameV2,
    ExplicitAttachmentFramesV2,
)
from joint_agent.functions.articulation_v2_controlled_distance import (
    ControlledDistanceContractV2,
)
from joint_agent.functions.articulation_v2_controlled_distance_usd import (
    ControlledDistanceStageReadbackV2,
    ControlledDistanceV2SourceReadbackProtocol,
)

ARTICULATION_V2_STATIC_CONTROLLED_DISTANCE_ADOPTION_SCHEMA_VERSION: Literal[
    "joint-agent-articulation-v2-static-controlled-distance-adoption-v2"
] = "joint-agent-articulation-v2-static-controlled-distance-adoption-v2"
ARTICULATION_V2_STATIC_CONTROLLED_DISTANCE_AUTHORING_SCHEMA_VERSION: Literal[
    "joint-agent-articulation-v2-static-controlled-distance-authoring-v2"
] = "joint-agent-articulation-v2-static-controlled-distance-authoring-v2"
ARTICULATION_V2_STATIC_CONTROLLED_DISTANCE_READBACK_SCHEMA_VERSION: Literal[
    "joint-agent-articulation-v2-static-controlled-distance-readback-v2"
] = "joint-agent-articulation-v2-static-controlled-distance-readback-v2"
ARTICULATION_V2_STATIC_CONTROLLED_DISTANCE_GATE3_CLAIM_SCHEMA_VERSION: Literal[
    "joint-agent-articulation-v2-static-controlled-distance-gate3-claim-v2"
] = "joint-agent-articulation-v2-static-controlled-distance-gate3-claim-v2"
ARTICULATION_V2_STATIC_CONTROLLED_DISTANCE_GATE3_CLOSEOUT_SCHEMA_VERSION: Literal[
    "joint-agent-articulation-v2-static-controlled-distance-gate3-closeout-v2"
] = "joint-agent-articulation-v2-static-controlled-distance-gate3-closeout-v2"
ARTICULATION_V2_STATIC_CONTROLLED_DISTANCE_RESULT_BUNDLE_SCHEMA_VERSION: Literal[
    "joint-agent-articulation-v2-static-controlled-distance-result-bundle-v2"
] = "joint-agent-articulation-v2-static-controlled-distance-result-bundle-v2"
ARTICULATION_V2_STATIC_CONTROLLED_DISTANCE_COMPLETION_SCHEMA_VERSION: Literal[
    "joint-agent-articulation-v2-static-controlled-distance-completion-v2"
] = "joint-agent-articulation-v2-static-controlled-distance-completion-v2"
ARTICULATION_V2_STATIC_CONTROLLED_DISTANCE_GATE3_FAILURE_SCHEMA_VERSION: Literal[
    "joint-agent-articulation-v2-static-controlled-distance-gate3-failure-v2"
] = "joint-agent-articulation-v2-static-controlled-distance-gate3-failure-v2"

_SHA256_LENGTH = 64


class _ReceiptModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid", frozen=True, strict=True, revalidate_instances="always"
    )


def _sha256(value: str, label: str) -> str:
    if len(value) != _SHA256_LENGTH or any(c not in "0123456789abcdef" for c in value):
        raise ValueError(f"{label} must be a lowercase SHA-256")
    return value


class ArticulationV2StaticControlledDistanceEvidenceBindingV2(_ReceiptModel):
    schema_version: Literal[
        "joint-agent-articulation-v2-static-controlled-distance-evidence-binding-v2"
    ]
    representation: Literal["prismatic_axial_interval_drive_body1_to_body0_v2"]
    run_plan_sha256: str
    intake_sha256: str
    run: ArticulationV2StaticControlledDistanceRunIdentityV2

    @field_validator("run_plan_sha256", "intake_sha256")
    @classmethod
    def _hashes(cls, value: str, info: Any) -> str:
        return _sha256(value, info.field_name)

    @model_validator(mode="after")
    def _one_representation(
        self,
    ) -> ArticulationV2StaticControlledDistanceEvidenceBindingV2:
        if self.representation != self.run.selected_source.representation:
            raise ValueError("V2 evidence binding mixes representations")
        return self


class ArticulationV2StaticControlledDistanceReceiptStageV2(_ReceiptModel):
    representation: Literal["prismatic_axial_interval_drive_body1_to_body0_v2"]
    plan: ArticulationV2StaticStagePlanV1
    command_sha256: str

    @field_validator("command_sha256")
    @classmethod
    def _command_hash(cls, value: str) -> str:
        return _sha256(value, "command_sha256")

    @model_validator(mode="after")
    def _canonical_command(
        self,
    ) -> ArticulationV2StaticControlledDistanceReceiptStageV2:
        from joint_agent.articulation_v2_static_execution_command import (
            articulation_v2_static_command_sha256,
        )

        if self.command_sha256 != articulation_v2_static_command_sha256(
            self.plan.command
        ):
            raise ValueError("V2 stage command digest differs from canonical command")
        return self


class ArticulationV2StaticControlledDistanceAdoptionReceiptV2(_ReceiptModel):
    schema_version: Literal[
        "joint-agent-articulation-v2-static-controlled-distance-adoption-v2"
    ]
    representation: Literal["prismatic_axial_interval_drive_body1_to_body0_v2"]
    binding: ArticulationV2StaticControlledDistanceEvidenceBindingV2
    stage: ArticulationV2StaticControlledDistanceReceiptStageV2
    status: ReceiptStatus
    contract_file: StaticReceiptFileV1
    selector_semantics_sha256: str

    @field_validator("selector_semantics_sha256")
    @classmethod
    def _semantic_hash(cls, value: str) -> str:
        return _sha256(value, "selector_semantics_sha256")

    @model_validator(mode="after")
    def _contract_stage(
        self,
    ) -> ArticulationV2StaticControlledDistanceAdoptionReceiptV2:
        if self.stage.plan.stage != "contract":
            raise ValueError("V2 adoption receipt requires the contract stage")
        _require_same_representation(self)
        return self


class ArticulationV2StaticControlledDistanceAuthoringReceiptV2(_ReceiptModel):
    schema_version: Literal[
        "joint-agent-articulation-v2-static-controlled-distance-authoring-v2"
    ]
    representation: Literal["prismatic_axial_interval_drive_body1_to_body0_v2"]
    binding: ArticulationV2StaticControlledDistanceEvidenceBindingV2
    stage: ArticulationV2StaticControlledDistanceReceiptStageV2
    status: ReceiptStatus
    adoption_receipt_sha256: str
    authoring_result: StaticReceiptFileV1
    generated_file: StaticReceiptFileV1 | None = None
    generated_identities: ArticulationV2StaticGeneratedArtifactIdentitiesV1 | None = (
        None
    )

    @field_validator("adoption_receipt_sha256")
    @classmethod
    def _adoption_hash(cls, value: str) -> str:
        return _sha256(value, "adoption_receipt_sha256")

    @model_validator(mode="after")
    def _authoring_stage(
        self,
    ) -> ArticulationV2StaticControlledDistanceAuthoringReceiptV2:
        if self.stage.plan.stage != "authoring":
            raise ValueError("V2 authoring receipt requires the authoring stage")
        if self.authoring_result.path != STATIC_EVIDENCE_AUTHORING_RESULT_PATH:
            raise ValueError("V2 authoring result uses an unadmitted evidence path")
        if (self.generated_file is None) != (self.generated_identities is None):
            raise ValueError("V2 generated file and identities must appear together")
        if self.status == "pass" and self.generated_identities is None:
            raise ValueError("passing V2 authoring requires generated bytes")
        if self.generated_file is not None and self.generated_identities is not None:
            _require_generated_file_matches_identities(
                self.generated_file, self.generated_identities
            )
        _require_same_representation(self)
        return self


class ArticulationV2StaticControlledDistanceComparisonChecksV2(_ReceiptModel):
    source_joint: bool
    endpoints: bool
    attachments: bool
    axis: bool
    axial_interval: bool
    drive: bool
    state: bool

    @property
    def passed(self) -> bool:
        return all(self.model_dump(mode="python").values())


class ArticulationV2StaticControlledDistanceReadbackReceiptV2(_ReceiptModel):
    schema_version: Literal[
        "joint-agent-articulation-v2-static-controlled-distance-readback-v2"
    ]
    representation: Literal["prismatic_axial_interval_drive_body1_to_body0_v2"]
    binding: ArticulationV2StaticControlledDistanceEvidenceBindingV2
    stage: ArticulationV2StaticControlledDistanceReceiptStageV2
    status: Literal["pass", "fail"]
    authoring_receipt_sha256: str
    generated_file: StaticReceiptFileV1
    generated_identities: ArticulationV2StaticGeneratedArtifactIdentitiesV1
    selector_semantics: ArticulationV2ControlledDistanceSelectorSemanticsV2
    expected: ControlledDistanceContractV2
    source_attachments: ExplicitAttachmentFramesV2
    observed: ControlledDistanceStageReadbackV2
    source_readback_protocol: ControlledDistanceV2SourceReadbackProtocol
    checks: ArticulationV2StaticControlledDistanceComparisonChecksV2

    @field_validator("authoring_receipt_sha256")
    @classmethod
    def _authoring_hash(cls, value: str) -> str:
        return _sha256(value, "authoring_receipt_sha256")

    @model_validator(mode="after")
    def _saved_stage_comparison(
        self,
    ) -> ArticulationV2StaticControlledDistanceReadbackReceiptV2:
        if self.stage.plan.stage != "readback":
            raise ValueError("V2 readback receipt requires the readback stage")
        _require_same_representation(self)
        _require_generated_file_matches_identities(
            self.generated_file, self.generated_identities
        )
        if self.selector_semantics.controlled_distance_contract != self.expected:
            raise ValueError(
                "V2 readback expected contract differs from selector semantics"
            )
        admitted_attachments = _controlled_distance_source_attachments(
            self.binding.run.selector.source_semantic_preimage
        )
        if self.source_attachments != admitted_attachments:
            raise ValueError(
                "V2 readback source attachments differ from selector admission"
            )
        expected_checks = articulation_v2_static_controlled_distance_comparison_checks(
            self.expected,
            self.observed,
            source_attachments=self.source_attachments,
        )
        if self.checks != expected_checks:
            raise ValueError("V2 readback checks differ from substantive comparison")
        if self.status != ("pass" if expected_checks.passed else "fail"):
            raise ValueError("V2 readback status differs from substantive comparison")
        return self


class ArticulationV2StaticControlledDistanceGate3ClaimV2(_ReceiptModel):
    schema_version: Literal[
        "joint-agent-articulation-v2-static-controlled-distance-gate3-claim-v2"
    ]
    representation: Literal["prismatic_axial_interval_drive_body1_to_body0_v2"]
    binding: ArticulationV2StaticControlledDistanceEvidenceBindingV2
    stage: ArticulationV2StaticControlledDistanceReceiptStageV2
    status: ReceiptStatus
    readback_receipt_sha256: str
    generated_file: StaticReceiptFileV1
    generated_identities: ArticulationV2StaticGeneratedArtifactIdentitiesV1
    raw_report: StaticReceiptFileV1
    stdout_log: StaticReceiptFileV1
    stderr_log: StaticReceiptFileV1
    support_evidence: StaticReceiptFileV1 | None = None

    @field_validator("readback_receipt_sha256")
    @classmethod
    def _readback_hash(cls, value: str) -> str:
        return _sha256(value, "readback_receipt_sha256")

    @model_validator(mode="after")
    def _gate3_stage(self) -> ArticulationV2StaticControlledDistanceGate3ClaimV2:
        stage = self.stage.plan.stage
        if stage not in {"gate3a", "gate3b"}:
            raise ValueError("V2 Gate 3 claim requires gate3a or gate3b")
        if self.raw_report.path != f"reports/{stage}.json":
            raise ValueError("V2 Gate 3 report path is unadmitted")
        if self.stdout_log.path != f"logs/{stage}.stdout.json":
            raise ValueError("V2 Gate 3 stdout path is unadmitted")
        if self.stderr_log.path != f"logs/{stage}.stderr.json":
            raise ValueError("V2 Gate 3 stderr path is unadmitted")
        if stage == "gate3a" and self.support_evidence is not None:
            raise ValueError("V2 Gate 3A cannot carry Gate 3B support")
        if stage == "gate3b" and (
            self.support_evidence is None
            or self.support_evidence.path != STATIC_EVIDENCE_GATE3B_SUPPORT_PATH
        ):
            raise ValueError("V2 Gate 3B requires support evidence")
        _require_generated_file_matches_identities(
            self.generated_file, self.generated_identities
        )
        _require_same_representation(self)
        return self


type ArticulationV2StaticControlledDistanceReceiptV2 = (
    ArticulationV2StaticControlledDistanceAdoptionReceiptV2
    | ArticulationV2StaticControlledDistanceAuthoringReceiptV2
    | ArticulationV2StaticControlledDistanceReadbackReceiptV2
    | ArticulationV2StaticControlledDistanceGate3ClaimV2
)


class ArticulationV2StaticControlledDistanceResultBundleV2(_ReceiptModel):
    schema_version: Literal[
        "joint-agent-articulation-v2-static-controlled-distance-result-bundle-v2"
    ]
    representation: Literal["prismatic_axial_interval_drive_body1_to_body0_v2"]
    adoption: ArticulationV2StaticControlledDistanceAdoptionReceiptV2
    authoring: ArticulationV2StaticControlledDistanceAuthoringReceiptV2
    readback: ArticulationV2StaticControlledDistanceReadbackReceiptV2
    gate3a: ArticulationV2StaticControlledDistanceGate3ClaimV2
    gate3b: ArticulationV2StaticControlledDistanceGate3ClaimV2

    @model_validator(mode="after")
    def _complete_chain(self) -> ArticulationV2StaticControlledDistanceResultBundleV2:
        receipts = (
            self.adoption,
            self.authoring,
            self.readback,
            self.gate3a,
            self.gate3b,
        )
        if any(item.representation != self.representation for item in receipts):
            raise ValueError("V2 result bundle mixes representations")
        if any(item.binding != self.adoption.binding for item in receipts[1:]):
            raise ValueError("V2 result bundle mixes evidence bindings")
        if tuple(item.stage.plan.stage for item in receipts) != (
            "contract",
            "authoring",
            "readback",
            "gate3a",
            "gate3b",
        ):
            raise ValueError("V2 result bundle stages are incomplete or substituted")
        if self.authoring.adoption_receipt_sha256 != controlled_distance_receipt_sha256(
            self.adoption
        ):
            raise ValueError("V2 authoring does not bind adoption")
        if self.readback.authoring_receipt_sha256 != controlled_distance_receipt_sha256(
            self.authoring
        ):
            raise ValueError("V2 readback does not bind authoring")
        readback_hash = controlled_distance_receipt_sha256(self.readback)
        if any(
            claim.readback_receipt_sha256 != readback_hash
            for claim in (self.gate3a, self.gate3b)
        ):
            raise ValueError("V2 Gate 3 claims do not bind readback")
        if any(item.status != "pass" for item in receipts[:3]):
            raise ValueError("V2 result bundle requires passing first three stages")
        if any(item.status == "error" for item in receipts[3:]):
            raise ValueError("V2 result bundle rejects Gate 3 execution errors")
        generated_file = self.authoring.generated_file
        generated = self.authoring.generated_identities
        if generated_file is None or generated is None:
            raise ValueError("V2 result bundle requires retained generated bytes")
        if any(
            item.generated_file != generated_file
            or item.generated_identities != generated
            for item in receipts[2:]
        ):
            raise ValueError("V2 downstream stages substitute generated bytes")
        return self


class ArticulationV2StaticControlledDistanceCompletionReceiptV2(_ReceiptModel):
    schema_version: Literal[
        "joint-agent-articulation-v2-static-controlled-distance-completion-v2"
    ]
    representation: Literal["prismatic_axial_interval_drive_body1_to_body0_v2"]
    binding: ArticulationV2StaticControlledDistanceEvidenceBindingV2
    evidence_paths: ArticulationV2StaticEvidencePathAllowlistV1
    generated_file: StaticReceiptFileV1
    generated_identities: ArticulationV2StaticGeneratedArtifactIdentitiesV1
    result_bundle: StaticReceiptFileV1
    retained_files: tuple[StaticReceiptFileV1, ...]
    terminal_receipt_path: Literal["completion.json"]
    dynamic_qualified: Literal[False]
    public_enabled: Literal[False]
    release_selection_applied: Literal[False]
    capability_manifest_updated: Literal[False]

    @field_validator("retained_files")
    @classmethod
    def _inventory(
        cls, value: tuple[StaticReceiptFileV1, ...]
    ) -> tuple[StaticReceiptFileV1, ...]:
        paths = tuple(item.path for item in value)
        if paths != tuple(sorted(paths)) or len(paths) != len(set(paths)):
            raise ValueError("V2 completion inventory must be sorted and unique")
        if STATIC_EVIDENCE_TERMINAL_RECEIPT_PATH in paths:
            raise ValueError("V2 completion cannot inventory itself")
        return value

    @model_validator(mode="after")
    def _exact_inventory(
        self,
    ) -> ArticulationV2StaticControlledDistanceCompletionReceiptV2:
        _require_same_representation(self)
        if self.terminal_receipt_path != self.evidence_paths.terminal_receipt:
            raise ValueError("V2 terminal path differs from evidence allowlist")
        if (
            tuple(item.path for item in self.retained_files)
            != self.evidence_paths.retained_paths
        ):
            raise ValueError("V2 completion inventory differs from evidence allowlist")
        by_path = {item.path: item for item in self.retained_files}
        _require_generated_file_matches_identities(
            self.generated_file, self.generated_identities
        )
        if by_path.get(self.generated_file.path) != self.generated_file:
            raise ValueError("V2 generated output is absent from completion inventory")
        if (
            self.result_bundle.path != STATIC_EVIDENCE_RESULT_BUNDLE_PATH
            or by_path.get(self.result_bundle.path) != self.result_bundle
        ):
            raise ValueError("V2 result bundle is absent from completion inventory")
        return self


class ArticulationV2StaticControlledDistanceGate3FailureReceiptV2(_ReceiptModel):
    schema_version: Literal[
        "joint-agent-articulation-v2-static-controlled-distance-gate3-failure-v2"
    ]
    representation: Literal["prismatic_axial_interval_drive_body1_to_body0_v2"]
    binding: ArticulationV2StaticControlledDistanceEvidenceBindingV2
    stage: ArticulationV2StaticControlledDistanceReceiptStageV2
    status: Literal["error"]
    failure_code: Literal[
        "articulation_v2_static_gate3a_report_missing_after_exit",
        "articulation_v2_static_gate3b_report_missing_after_exit",
    ]
    failure_detail: str
    report_observation: Literal["missing"]
    expected_report_path: Literal["reports/gate3a.json", "reports/gate3b.json"]
    returncode: int = Field(ge=-255, le=255)
    termination_reason: Literal[
        "exited",
        "outer_deadline_exceeded",
        "output_limit_exceeded",
        "containment_failure",
    ]
    generated_file: StaticReceiptFileV1
    generated_identities: ArticulationV2StaticGeneratedArtifactIdentitiesV1
    stdout_log: StaticReceiptFileV1
    stderr_log: StaticReceiptFileV1
    retained_files: tuple[StaticReceiptFileV1, ...]
    terminal_receipt_path: Literal["failure.json"]
    static_qualified: Literal[False]
    dynamic_qualified: Literal[False]
    public_enabled: Literal[False]
    release_selection_applied: Literal[False]
    capability_manifest_updated: Literal[False]

    @field_validator("failure_detail")
    @classmethod
    def _detail(cls, value: str) -> str:
        if not value or len(value) > 4096 or "\x00" in value:
            raise ValueError("V2 Gate 3 failure detail must be nonempty and bounded")
        return value

    @field_validator("retained_files")
    @classmethod
    def _failure_inventory(
        cls, value: tuple[StaticReceiptFileV1, ...]
    ) -> tuple[StaticReceiptFileV1, ...]:
        paths = tuple(item.path for item in value)
        if paths != tuple(sorted(paths)) or len(paths) != len(set(paths)):
            raise ValueError("V2 failure inventory must be sorted and unique")
        if STATIC_EVIDENCE_GATE3_FAILURE_RECEIPT_PATH in paths:
            raise ValueError("V2 failure receipt cannot inventory itself")
        return value

    @model_validator(mode="after")
    def _failure_stage(
        self,
    ) -> ArticulationV2StaticControlledDistanceGate3FailureReceiptV2:
        stage = self.stage.plan.stage
        if stage not in {"gate3a", "gate3b"}:
            raise ValueError("V2 Gate 3 failure requires a Gate 3 stage")
        _require_same_representation(self)
        _require_generated_file_matches_identities(
            self.generated_file, self.generated_identities
        )
        if (
            self.failure_code
            != f"articulation_v2_static_{stage}_report_missing_after_exit"
        ):
            raise ValueError("V2 Gate 3 failure code differs from stage")
        if self.expected_report_path != f"reports/{stage}.json":
            raise ValueError("V2 Gate 3 expected report differs from stage")
        if (
            self.stdout_log.path != f"logs/{stage}.stdout.json"
            or self.stderr_log.path != f"logs/{stage}.stderr.json"
        ):
            raise ValueError("V2 Gate 3 failure logs use unadmitted paths")
        path_builder = (
            articulation_v2_static_gate3a_failure_paths
            if stage == "gate3a"
            else articulation_v2_static_gate3b_failure_paths
        )
        expected = tuple(
            path
            for path in path_builder(
                constraint_kind="distance", generated_output=self.generated_file.path
            )
            if path != STATIC_EVIDENCE_GATE3_FAILURE_RECEIPT_PATH
        )
        if tuple(item.path for item in self.retained_files) != expected:
            raise ValueError("V2 Gate 3 failure inventory differs from contract")
        by_path = {item.path: item for item in self.retained_files}
        if by_path.get(self.generated_file.path) != self.generated_file:
            raise ValueError("V2 Gate 3 failure output differs from inventory")
        if by_path.get(self.stdout_log.path) != self.stdout_log:
            raise ValueError("V2 Gate 3 failure stdout differs from inventory")
        if by_path.get(self.stderr_log.path) != self.stderr_log:
            raise ValueError("V2 Gate 3 failure stderr differs from inventory")
        return self


def articulation_v2_static_controlled_distance_comparison_checks(
    expected: ControlledDistanceContractV2,
    observed: ControlledDistanceStageReadbackV2,
    *,
    source_attachments: ExplicitAttachmentFramesV2,
) -> ArticulationV2StaticControlledDistanceComparisonChecksV2:
    if (
        type(expected) is not ControlledDistanceContractV2
        or type(observed) is not ControlledDistanceStageReadbackV2
        or type(source_attachments) is not ExplicitAttachmentFramesV2
    ):
        raise TypeError("V2 comparison requires exact controlled-distance models")
    expected_attachments = _project_attachments(
        source_attachments,
        meters_per_unit=observed.meters_per_unit,
    )
    return ArticulationV2StaticControlledDistanceComparisonChecksV2(
        source_joint=expected.source_joint_path == observed.joint_path,
        endpoints=(
            expected.body0_prim_path == observed.body0_prim_path
            and expected.body1_prim_path == observed.body1_prim_path
        ),
        attachments=expected_attachments == observed.attachments,
        axis=expected.axis_stage == observed.axis_stage,
        axial_interval=expected.axial_interval == observed.axial_interval,
        drive=expected.drive == observed.drive,
        state=expected.state == observed.state,
    )


def _controlled_distance_source_attachments(
    preimage: ControlledDistanceSelectorSemanticPreimageV2,
) -> ExplicitAttachmentFramesV2:
    attributes = preimage.joint.authored_metadata.physics_attributes
    scale = preimage.stage.meters_per_unit
    return ExplicitAttachmentFramesV2(
        kind="explicit",
        body0=AttachmentFrameV2(
            position_meters=_scaled_vector(
                attributes["physics:localPos0"],
                scale,
                label="controlled-distance body0 attachment",
            ),
            orientation_wxyz=_quaternion(
                attributes["physics:localRot0"],
                label="controlled-distance body0 orientation",
            ),
        ),
        body1=AttachmentFrameV2(
            position_meters=_scaled_vector(
                attributes["physics:localPos1"],
                scale,
                label="controlled-distance body1 attachment",
            ),
            orientation_wxyz=_quaternion(
                attributes["physics:localRot1"],
                label="controlled-distance body1 orientation",
            ),
        ),
    )


def _project_attachments(
    attachments: ExplicitAttachmentFramesV2,
    *,
    meters_per_unit: float,
) -> ExplicitAttachmentFramesV2:
    if not math.isfinite(meters_per_unit) or meters_per_unit <= 0.0:
        raise ValueError("V2 saved readback stage scale must be finite and positive")

    def project(value: float, units: float) -> float:
        try:
            result = struct.unpack("!f", struct.pack("!f", value / units))[0] * units
        except (OverflowError, struct.error) as exc:
            raise ValueError("V2 attachment is not representable as binary32") from exc
        if not math.isfinite(result):
            raise ValueError("V2 attachment is not finite after binary32 projection")
        return 0.0 if result == 0.0 else result

    def frame(value: AttachmentFrameV2) -> AttachmentFrameV2:
        return AttachmentFrameV2(
            position_meters=tuple(
                project(item, meters_per_unit) for item in value.position_meters
            ),
            orientation_wxyz=tuple(
                project(item, 1.0) for item in value.orientation_wxyz
            ),
        )

    return ExplicitAttachmentFramesV2(
        kind="explicit",
        body0=frame(attachments.body0),
        body1=frame(attachments.body1),
    )


_ModelT = TypeVar("_ModelT", bound=BaseModel)


def _canonical(value: _ModelT, model: type[_ModelT]) -> bytes:
    if type(value) is not model:
        raise TypeError(f"value must be an exact {model.__name__}")
    adapter = TypeAdapter(model)
    payload = json.dumps(
        adapter.dump_python(value, mode="json"),
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
        allow_nan=False,
    ).encode("utf-8")
    validated = adapter.validate_json(payload, strict=True)
    return json.dumps(
        adapter.dump_python(validated, mode="json"),
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
        allow_nan=False,
    ).encode("utf-8")


def canonical_articulation_v2_static_controlled_distance_receipt_bytes(
    receipt: ArticulationV2StaticControlledDistanceReceiptV2,
) -> bytes:
    allowed = (
        ArticulationV2StaticControlledDistanceAdoptionReceiptV2,
        ArticulationV2StaticControlledDistanceAuthoringReceiptV2,
        ArticulationV2StaticControlledDistanceReadbackReceiptV2,
        ArticulationV2StaticControlledDistanceGate3ClaimV2,
    )
    if type(receipt) not in allowed:
        raise TypeError("receipt must be an exact controlled-distance-v2 receipt")
    return _canonical(receipt, type(receipt))


def controlled_distance_receipt_sha256(
    receipt: ArticulationV2StaticControlledDistanceReceiptV2,
) -> str:
    return hashlib.sha256(
        canonical_articulation_v2_static_controlled_distance_receipt_bytes(receipt)
    ).hexdigest()


def canonical_articulation_v2_static_controlled_distance_result_bundle_bytes(
    bundle: ArticulationV2StaticControlledDistanceResultBundleV2,
) -> bytes:
    return _canonical(bundle, ArticulationV2StaticControlledDistanceResultBundleV2)


def canonical_articulation_v2_static_controlled_distance_completion_bytes(
    receipt: ArticulationV2StaticControlledDistanceCompletionReceiptV2,
) -> bytes:
    return _canonical(
        receipt, ArticulationV2StaticControlledDistanceCompletionReceiptV2
    )


def canonical_articulation_v2_static_controlled_distance_failure_bytes(
    receipt: ArticulationV2StaticControlledDistanceGate3FailureReceiptV2,
) -> bytes:
    return _canonical(
        receipt, ArticulationV2StaticControlledDistanceGate3FailureReceiptV2
    )


def controlled_distance_completion_sha256(
    receipt: ArticulationV2StaticControlledDistanceCompletionReceiptV2,
) -> str:
    return hashlib.sha256(
        canonical_articulation_v2_static_controlled_distance_completion_bytes(receipt)
    ).hexdigest()


def canonical_articulation_v2_static_controlled_distance_gate3_closeout_bytes(
    plan: ArticulationV2StaticControlledDistanceRunPlanV2,
    intake: ArticulationV2StaticControlledDistanceIntakeV2,
    generated: ArticulationV2StaticGeneratedArtifactIdentitiesV1,
) -> bytes:
    if (
        type(plan) is not ArticulationV2StaticControlledDistanceRunPlanV2
        or type(intake) is not ArticulationV2StaticControlledDistanceIntakeV2
        or type(generated) is not ArticulationV2StaticGeneratedArtifactIdentitiesV1
    ):
        raise TypeError("V2 Gate 3 closeout requires exact sibling inputs")
    gate3 = generated.gate3
    document = {
        "schema_version": ARTICULATION_V2_STATIC_CONTROLLED_DISTANCE_GATE3_CLOSEOUT_SCHEMA_VERSION,
        "representation": ARTICULATION_V2_STATIC_CONTROLLED_DISTANCE_REPRESENTATION,
        "run_id": plan.run.run_id,
        "run_plan_sha256": articulation_v2_static_controlled_distance_run_plan_sha256(
            plan
        ),
        "intake_sha256": articulation_v2_static_controlled_distance_intake_sha256(
            intake
        ),
        "generated_artifact": {
            "uri": gate3.uri,
            "root_sha256": gate3.root_sha256,
            "dependency_bundle_schema_version": gate3.dependency_bundle_schema_version,
            "dependency_bundle_sha256": gate3.dependency_bundle_sha256,
            "dependency_bundle_entry_count": gate3.dependency_bundle_entry_count,
        },
        "assets": [
            {
                "asset_id": plan.run.selector.release_gate_asset_id,
                "generated_usd_path": plan.output.output_key,
            }
        ],
    }
    return json.dumps(
        document,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=True,
        allow_nan=False,
    ).encode("utf-8")


def validate_articulation_v2_static_controlled_distance_result_bundle(
    loaded: LoadedCapabilityManifest,
    plan: ArticulationV2StaticControlledDistanceRunPlanV2,
    intake: ArticulationV2StaticControlledDistanceIntakeV2,
    bundle: ArticulationV2StaticControlledDistanceResultBundleV2,
) -> None:
    plan = _revalidate_articulation_v2_static_controlled_distance_run_plan(plan)
    intake = _revalidate_articulation_v2_static_controlled_distance_intake(intake)
    bundle = _revalidate_bundle(bundle)
    validate_articulation_v2_static_controlled_distance_intake(loaded, plan, intake)
    expected_binding = _binding(plan, intake)
    receipts = (
        bundle.adoption,
        bundle.authoring,
        bundle.readback,
        bundle.gate3a,
        bundle.gate3b,
    )
    if any(item.binding != expected_binding for item in receipts):
        raise CapabilityManifestError(
            "V2 bundle substitutes run-plan, intake, or source identity"
        )
    for receipt, stage in zip(receipts, plan.stages.ordered(), strict=True):
        if cast(Any, receipt).stage.plan != stage:
            raise CapabilityManifestError(f"V2 bundle substitutes {stage.stage} stage")
    if bundle.adoption.contract_file != StaticReceiptFileV1(
        path=intake.contract_uri,
        size_bytes=intake.contract_size_bytes,
        sha256=intake.contract_sha256,
    ):
        raise CapabilityManifestError("V2 adoption differs from exact intake contract")
    if (
        bundle.adoption.selector_semantics_sha256
        != articulation_v2_controlled_distance_selector_semantics_sha256(
            intake.contract_semantics
        )
    ):
        raise CapabilityManifestError(
            "V2 adoption semantic identity differs from intake"
        )
    if (
        bundle.readback.selector_semantics != intake.contract_semantics
        or bundle.readback.expected
        != intake.contract_semantics.controlled_distance_contract
    ):
        raise CapabilityManifestError("V2 saved readback differs from intake semantics")
    generated = bundle.authoring.generated_identities
    if generated is None or generated.authorer.uri != plan.output.output_key:
        raise CapabilityManifestError("V2 authoring differs from planned output")


def validate_articulation_v2_static_controlled_distance_completion(
    loaded: LoadedCapabilityManifest,
    plan: ArticulationV2StaticControlledDistanceRunPlanV2,
    intake: ArticulationV2StaticControlledDistanceIntakeV2,
    bundle: ArticulationV2StaticControlledDistanceResultBundleV2,
    completion: ArticulationV2StaticControlledDistanceCompletionReceiptV2,
) -> None:
    completion = _revalidate_completion(completion)
    validate_articulation_v2_static_controlled_distance_result_bundle(
        loaded, plan, intake, bundle
    )
    if completion.binding != _binding(plan, intake):
        raise CapabilityManifestError("V2 completion substitutes run identity")
    if completion.evidence_paths != plan.evidence_paths:
        raise CapabilityManifestError("V2 completion substitutes evidence paths")
    if (
        completion.generated_identities != bundle.authoring.generated_identities
        or completion.generated_file != bundle.authoring.generated_file
    ):
        raise CapabilityManifestError("V2 completion substitutes generated identities")
    expected = _expected_completion_files(plan, intake, bundle)
    actual = {item.path: item for item in completion.retained_files}
    for path, record in expected.items():
        if actual.get(path) != record:
            raise CapabilityManifestError(
                f"V2 completion retained identity differs for {path}"
            )


def _expected_completion_files(
    plan: ArticulationV2StaticControlledDistanceRunPlanV2,
    intake: ArticulationV2StaticControlledDistanceIntakeV2,
    bundle: ArticulationV2StaticControlledDistanceResultBundleV2,
) -> dict[str, StaticReceiptFileV1]:
    generated_file = bundle.authoring.generated_file
    generated = bundle.authoring.generated_identities
    support = bundle.gate3b.support_evidence
    if generated_file is None or generated is None or support is None:
        raise CapabilityManifestError(
            "V2 completion is missing required retained bytes"
        )
    return {
        STATIC_EVIDENCE_RUN_PLAN_PATH: _model_file(
            STATIC_EVIDENCE_RUN_PLAN_PATH,
            canonical_articulation_v2_static_controlled_distance_run_plan_bytes(plan),
        ),
        STATIC_EVIDENCE_INTAKE_PATH: _model_file(
            STATIC_EVIDENCE_INTAKE_PATH,
            canonical_articulation_v2_static_controlled_distance_intake_bytes(intake),
        ),
        STATIC_EVIDENCE_GATE3_CLOSEOUT_PATH: _model_file(
            STATIC_EVIDENCE_GATE3_CLOSEOUT_PATH,
            canonical_articulation_v2_static_controlled_distance_gate3_closeout_bytes(
                plan, intake, generated
            ),
        ),
        intake.contract_uri: bundle.adoption.contract_file,
        STATIC_EVIDENCE_AUTHORING_RESULT_PATH: bundle.authoring.authoring_result,
        generated_file.path: generated_file,
        "receipts/contract.json": _model_file(
            "receipts/contract.json",
            canonical_articulation_v2_static_controlled_distance_receipt_bytes(
                bundle.adoption
            ),
        ),
        "receipts/authoring.json": _model_file(
            "receipts/authoring.json",
            canonical_articulation_v2_static_controlled_distance_receipt_bytes(
                bundle.authoring
            ),
        ),
        "receipts/readback.json": _model_file(
            "receipts/readback.json",
            canonical_articulation_v2_static_controlled_distance_receipt_bytes(
                bundle.readback
            ),
        ),
        "claims/gate3a.json": _model_file(
            "claims/gate3a.json",
            canonical_articulation_v2_static_controlled_distance_receipt_bytes(
                bundle.gate3a
            ),
        ),
        "claims/gate3b.json": _model_file(
            "claims/gate3b.json",
            canonical_articulation_v2_static_controlled_distance_receipt_bytes(
                bundle.gate3b
            ),
        ),
        bundle.gate3a.raw_report.path: bundle.gate3a.raw_report,
        bundle.gate3b.raw_report.path: bundle.gate3b.raw_report,
        bundle.gate3a.stdout_log.path: bundle.gate3a.stdout_log,
        bundle.gate3a.stderr_log.path: bundle.gate3a.stderr_log,
        bundle.gate3b.stdout_log.path: bundle.gate3b.stdout_log,
        bundle.gate3b.stderr_log.path: bundle.gate3b.stderr_log,
        STATIC_EVIDENCE_GATE3B_SUPPORT_PATH: support,
        STATIC_EVIDENCE_RESULT_BUNDLE_PATH: _model_file(
            STATIC_EVIDENCE_RESULT_BUNDLE_PATH,
            canonical_articulation_v2_static_controlled_distance_result_bundle_bytes(
                bundle
            ),
        ),
    }


def _binding(
    plan: ArticulationV2StaticControlledDistanceRunPlanV2,
    intake: ArticulationV2StaticControlledDistanceIntakeV2,
) -> ArticulationV2StaticControlledDistanceEvidenceBindingV2:
    return ArticulationV2StaticControlledDistanceEvidenceBindingV2(
        schema_version="joint-agent-articulation-v2-static-controlled-distance-evidence-binding-v2",
        representation=ARTICULATION_V2_STATIC_CONTROLLED_DISTANCE_REPRESENTATION,
        run_plan_sha256=articulation_v2_static_controlled_distance_run_plan_sha256(
            plan
        ),
        intake_sha256=articulation_v2_static_controlled_distance_intake_sha256(intake),
        run=plan.run,
    )


def _revalidate_bundle(
    value: ArticulationV2StaticControlledDistanceResultBundleV2,
) -> ArticulationV2StaticControlledDistanceResultBundleV2:
    try:
        return TypeAdapter(
            ArticulationV2StaticControlledDistanceResultBundleV2
        ).validate_json(
            canonical_articulation_v2_static_controlled_distance_result_bundle_bytes(
                value
            ),
            strict=True,
        )
    except (TypeError, ValueError) as exc:
        raise CapabilityManifestError(
            "V2 result bundle fails strict revalidation"
        ) from exc


def _revalidate_completion(
    value: ArticulationV2StaticControlledDistanceCompletionReceiptV2,
) -> ArticulationV2StaticControlledDistanceCompletionReceiptV2:
    try:
        return TypeAdapter(
            ArticulationV2StaticControlledDistanceCompletionReceiptV2
        ).validate_json(
            canonical_articulation_v2_static_controlled_distance_completion_bytes(
                value
            ),
            strict=True,
        )
    except (TypeError, ValueError) as exc:
        raise CapabilityManifestError(
            "V2 completion fails strict revalidation"
        ) from exc


def _model_file(path: str, payload: bytes) -> StaticReceiptFileV1:
    return StaticReceiptFileV1(
        path=path, size_bytes=len(payload), sha256=hashlib.sha256(payload).hexdigest()
    )


def _require_same_representation(value: Any) -> None:
    stage = getattr(value, "stage", None)
    if (
        value.representation
        != ARTICULATION_V2_STATIC_CONTROLLED_DISTANCE_REPRESENTATION
        or value.binding.representation
        != ARTICULATION_V2_STATIC_CONTROLLED_DISTANCE_REPRESENTATION
        or (
            stage is not None
            and stage.representation
            != ARTICULATION_V2_STATIC_CONTROLLED_DISTANCE_REPRESENTATION
        )
    ):
        raise ValueError("controlled-distance-v2 receipt mixes representations")


def _require_generated_file_matches_identities(
    generated_file: StaticReceiptFileV1,
    identities: ArticulationV2StaticGeneratedArtifactIdentitiesV1,
) -> None:
    if (
        generated_file.path != identities.authorer.uri
        or generated_file.sha256 != identities.authorer.root_sha256
    ):
        raise ValueError("V2 generated file differs from dual URI/root identities")


__all__ = [
    "ARTICULATION_V2_STATIC_CONTROLLED_DISTANCE_ADOPTION_SCHEMA_VERSION",
    "ARTICULATION_V2_STATIC_CONTROLLED_DISTANCE_AUTHORING_SCHEMA_VERSION",
    "ARTICULATION_V2_STATIC_CONTROLLED_DISTANCE_COMPLETION_SCHEMA_VERSION",
    "ARTICULATION_V2_STATIC_CONTROLLED_DISTANCE_GATE3_CLAIM_SCHEMA_VERSION",
    "ARTICULATION_V2_STATIC_CONTROLLED_DISTANCE_GATE3_CLOSEOUT_SCHEMA_VERSION",
    "ARTICULATION_V2_STATIC_CONTROLLED_DISTANCE_GATE3_FAILURE_SCHEMA_VERSION",
    "ARTICULATION_V2_STATIC_CONTROLLED_DISTANCE_READBACK_SCHEMA_VERSION",
    "ARTICULATION_V2_STATIC_CONTROLLED_DISTANCE_RESULT_BUNDLE_SCHEMA_VERSION",
    "ArticulationV2StaticControlledDistanceAdoptionReceiptV2",
    "ArticulationV2StaticControlledDistanceAuthoringReceiptV2",
    "ArticulationV2StaticControlledDistanceComparisonChecksV2",
    "ArticulationV2StaticControlledDistanceCompletionReceiptV2",
    "ArticulationV2StaticControlledDistanceEvidenceBindingV2",
    "ArticulationV2StaticControlledDistanceGate3ClaimV2",
    "ArticulationV2StaticControlledDistanceGate3FailureReceiptV2",
    "ArticulationV2StaticControlledDistanceReadbackReceiptV2",
    "ArticulationV2StaticControlledDistanceReceiptStageV2",
    "ArticulationV2StaticControlledDistanceReceiptV2",
    "ArticulationV2StaticControlledDistanceResultBundleV2",
    "articulation_v2_static_controlled_distance_comparison_checks",
    "canonical_articulation_v2_static_controlled_distance_completion_bytes",
    "canonical_articulation_v2_static_controlled_distance_failure_bytes",
    "canonical_articulation_v2_static_controlled_distance_gate3_closeout_bytes",
    "canonical_articulation_v2_static_controlled_distance_receipt_bytes",
    "canonical_articulation_v2_static_controlled_distance_result_bundle_bytes",
    "controlled_distance_completion_sha256",
    "controlled_distance_receipt_sha256",
    "validate_articulation_v2_static_controlled_distance_completion",
    "validate_articulation_v2_static_controlled_distance_result_bundle",
]
