# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""SimReady verifier — static geometric checks on cad_kernel output.

Phase 1 scope is direct OCP/OCCT static checks. Physics drop-test via
Isaac Sim + Kit Inspector `/execute` is Phase 2 (needs Kit Inspector wired).
"""

from .checks import (
    VerifyReport,
    all_checks,
    bbox_check,
    has_planar_mounting_face_check,
    has_volume,
    interference_check,
    manifold_check,
    oversize_check,
    self_intersect_check,
    thin_wall_check,
    volume_check,
)
from .dfm import (
    DFMConfig,
    all_dfm_checks,
    draft_angle_check,
    min_hole_check,
    min_wall_check,
    overhang_check,
    sharp_internal_corner_check,
    undercut_check,
)
from .sim_ready import (
    ARTICULATED_PROFILE_ID,
    INSERTION_FIXTURE_PROFILE_ID,
    RIGID_DYNAMIC_PROFILE_ID,
    ROBOTICS_MANIPULATION_PROFILE_ID,
    SIM_READY_PROFILE_ID,
    SIM_READY_PROFILES,
    STATIC_VISUAL_PROFILE_ID,
    SimReadyCertificate,
    SimReadyIssue,
    SimReadyLevel,
    SimReadyProfile,
    SimReadyReport,
    audit_usd_geometry_handoff,
    audit_usd_mesh_topology,
    audit_usd_physics_authoring,
    audit_usd_physics_materials,
    author_placeholder_simready_demo,
    build_sim_ready_certificate,
    local_runtime_smoke,
    repair_usd_for_simready,
    resolve_sim_ready_profile,
    validate_result_for_sim,
)
from .simready_authoring import (
    SIMREADY_AUTHORING_SCHEMA,
    author_simready_package,
)

__all__ = [
    "all_checks",
    "all_dfm_checks",
    "bbox_check",
    "DFMConfig",
    "draft_angle_check",
    "has_planar_mounting_face_check",
    "has_volume",
    "interference_check",
    "manifold_check",
    "min_hole_check",
    "min_wall_check",
    "overhang_check",
    "oversize_check",
    "self_intersect_check",
    "ARTICULATED_PROFILE_ID",
    "INSERTION_FIXTURE_PROFILE_ID",
    "RIGID_DYNAMIC_PROFILE_ID",
    "ROBOTICS_MANIPULATION_PROFILE_ID",
    "SIM_READY_PROFILE_ID",
    "SIM_READY_PROFILES",
    "STATIC_VISUAL_PROFILE_ID",
    "SimReadyProfile",
    "SimReadyCertificate",
    "SimReadyIssue",
    "SimReadyLevel",
    "SimReadyReport",
    "audit_usd_geometry_handoff",
    "audit_usd_mesh_topology",
    "audit_usd_physics_authoring",
    "audit_usd_physics_materials",
    "author_placeholder_simready_demo",
    "build_sim_ready_certificate",
    "local_runtime_smoke",
    "repair_usd_for_simready",
    "resolve_sim_ready_profile",
    "sharp_internal_corner_check",
    "thin_wall_check",
    "undercut_check",
    "validate_result_for_sim",
    "volume_check",
    "VerifyReport",
    "SIMREADY_AUTHORING_SCHEMA",
    "author_simready_package",
]
