# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""SimReady Foundation workflow adapters."""

from .collision_filter_completion import (
    COLLISION_FILTER_COMPLETION_SCHEMA_VERSION,
    CollisionFilterCompletionError,
    CollisionFilterCompletionRequestV1,
    CollisionFilterCompletionResult,
    generate_collision_filter_completion_plan,
)
from .collision_filter_plan import (
    COLLISION_FILTER_PLAN_SCHEMA_VERSION,
    COLLISION_FILTER_RECEIPT_SCHEMA_VERSION,
    CollisionFilterEvidence,
    CollisionFilterPair,
    CollisionFilterPlan,
    CollisionFilterPlanProvenance,
    CollisionFilterResult,
    author_collision_filter_derivative,
    filtered_pair_is_authored,
)
from .conform_profile import run_simready_profile_conformance
from .gate3a_hygiene import (
    GATE3A_HYGIENE_REQUIREMENT,
    Gate3AHygieneResult,
    Gate3APhysicsInventory,
    inspect_gate3a_physics_inventory,
    repair_gate3a_hygiene,
)
from .gate3a_stage_metadata import (
    GATE3A_STAGE_METADATA_PLAN_SCHEMA_VERSION,
    GATE3A_STAGE_METADATA_RECEIPT_SCHEMA_VERSION,
    GATE3A_STAGE_METADATA_REQUIREMENT,
    Gate3AStageMetadataPlan,
    Gate3AStageMetadataResult,
    StageMetadataEvidence,
    StageMetadataKindOpinion,
    StageMetadataLinearQuantity,
    StageMetadataProvenance,
    StageMetadataTransformScale,
    author_gate3a_stage_metadata_derivative,
)
from .grasp_plan_generator import (
    GraspPlanGenerationError,
    SimReadyGraspPlanGenerationResult,
    generate_simready_grasp_plan,
)
from .models import (
    DEFAULT_SIMREADY_FOUNDATION_REF,
    DEFAULT_SIMREADY_FOUNDATION_REPO_URL,
    DEFAULT_SIMREADY_PROFILE,
    DEFAULT_SIMREADY_PROFILE_VERSION,
    SimReadyConformanceInput,
    SimReadyConformanceReport,
    SimReadyGraspPlan,
    SimReadyGraspPlanAnalyticMachineProvenance,
    SimReadyGraspPlanAnalyticSurfaceProof,
    SimReadyGraspPlanComposedMachineProvenance,
    SimReadyGraspPlanMachineProvenance,
    SimReadyPreflightReport,
    SimReadyRuntimeInfo,
    SimReadyValidationInput,
    SimReadyValidationReport,
)
from .physics_profile_plan import (
    PHYSICS_PROFILE_PLAN_SCHEMA_VERSION,
    PHYSICS_PROFILE_RECEIPT_SCHEMA_VERSION,
    PhysicsColliderApproximationPlanV1,
    PhysicsMaterialAuthoredOpinionsV1,
    PhysicsMaterialPlanV1,
    PhysicsProfileApprovalV1,
    PhysicsProfileAuthoredSdfTransitionV1,
    PhysicsProfilePlanError,
    PhysicsProfilePlanResult,
    PhysicsProfilePlanV1,
    PhysicsProfilePreservedApproximationV1,
    PhysicsProfileReceiptV1,
    PhysicsProfileSourceIdentity,
    author_physics_profile_plan,
    inspect_physics_profile_source,
    load_physics_profile_plan,
    verify_physics_profile_receipt,
)
from .preflight import preflight_simready_foundation
from .validate_profile import run_simready_profile_validation

__all__ = [
    "COLLISION_FILTER_COMPLETION_SCHEMA_VERSION",
    "COLLISION_FILTER_PLAN_SCHEMA_VERSION",
    "COLLISION_FILTER_RECEIPT_SCHEMA_VERSION",
    "DEFAULT_SIMREADY_FOUNDATION_REF",
    "DEFAULT_SIMREADY_FOUNDATION_REPO_URL",
    "DEFAULT_SIMREADY_PROFILE",
    "DEFAULT_SIMREADY_PROFILE_VERSION",
    "GraspPlanGenerationError",
    "GATE3A_STAGE_METADATA_PLAN_SCHEMA_VERSION",
    "GATE3A_STAGE_METADATA_RECEIPT_SCHEMA_VERSION",
    "GATE3A_STAGE_METADATA_REQUIREMENT",
    "Gate3AStageMetadataPlan",
    "Gate3AStageMetadataResult",
    "CollisionFilterEvidence",
    "CollisionFilterCompletionError",
    "CollisionFilterCompletionRequestV1",
    "CollisionFilterCompletionResult",
    "CollisionFilterPair",
    "CollisionFilterPlan",
    "CollisionFilterPlanProvenance",
    "CollisionFilterResult",
    "GATE3A_HYGIENE_REQUIREMENT",
    "Gate3AHygieneResult",
    "Gate3APhysicsInventory",
    "PHYSICS_PROFILE_PLAN_SCHEMA_VERSION",
    "PHYSICS_PROFILE_RECEIPT_SCHEMA_VERSION",
    "PhysicsColliderApproximationPlanV1",
    "PhysicsMaterialAuthoredOpinionsV1",
    "PhysicsMaterialPlanV1",
    "PhysicsProfileApprovalV1",
    "PhysicsProfileAuthoredSdfTransitionV1",
    "PhysicsProfilePlanError",
    "PhysicsProfilePlanResult",
    "PhysicsProfilePlanV1",
    "PhysicsProfileReceiptV1",
    "PhysicsProfilePreservedApproximationV1",
    "PhysicsProfileSourceIdentity",
    "SimReadyConformanceInput",
    "SimReadyConformanceReport",
    "SimReadyGraspPlan",
    "SimReadyGraspPlanAnalyticMachineProvenance",
    "SimReadyGraspPlanAnalyticSurfaceProof",
    "SimReadyGraspPlanComposedMachineProvenance",
    "SimReadyGraspPlanGenerationResult",
    "SimReadyGraspPlanMachineProvenance",
    "SimReadyPreflightReport",
    "SimReadyRuntimeInfo",
    "SimReadyValidationInput",
    "SimReadyValidationReport",
    "StageMetadataEvidence",
    "StageMetadataKindOpinion",
    "StageMetadataLinearQuantity",
    "StageMetadataProvenance",
    "StageMetadataTransformScale",
    "author_gate3a_stage_metadata_derivative",
    "generate_simready_grasp_plan",
    "generate_collision_filter_completion_plan",
    "author_collision_filter_derivative",
    "filtered_pair_is_authored",
    "author_physics_profile_plan",
    "inspect_physics_profile_source",
    "load_physics_profile_plan",
    "verify_physics_profile_receipt",
    "preflight_simready_foundation",
    "inspect_gate3a_physics_inventory",
    "repair_gate3a_hygiene",
    "run_simready_profile_conformance",
    "run_simready_profile_validation",
]
