# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""Task for loading generate-reference-image configuration from YAML.

This thin config task maps the material agent step config keys to the
context keys expected by ``GenerateReferenceImageTask``.
"""

import logging
from pathlib import Path
from typing import Any

from world_understanding.agentic.config import log_config_source
from world_understanding.agentic.events import get_listener
from world_understanding.agentic.tasks import Task
from world_understanding.utils.credentials import (
    create_directory_with_safe_diagnostics,
    redact_sensitive_config,
    redact_sensitive_path,
    resolve_path_with_safe_diagnostics,
)

from material_agent.tasks.config_loader import load_config_from_context

logger = logging.getLogger(__name__)


class GenerateRefImageConfigTask(Task):
    """Load generate-reference-image configuration.

    Same pattern as ``RenderPreviewConfigTask``: load the in-memory step
    config (or standalone YAML) and populate downstream context keys.

    Input context keys:
        - config_dict: In-memory step configuration (preferred)
        - config_path: YAML path or relative-path anchor

    Output context keys:
        - rendered_preview_paths: list[str] — preview images
        - reference_images: list[str] — optional existing reference images
        - image_gen_config: dict — backend + model settings
        - image_gen_prompt: str — user description of desired look
        - output_dir: str — save directory
        - num_images: int — how many images to generate
    """

    def __init__(self) -> None:
        self.name = "GenerateRefImageConfig"
        self.description = "Load generate-reference-image configuration"

    def run(self, context: dict[str, Any], object_store=None) -> dict[str, Any]:
        listener = get_listener(context, logger_name=__name__)
        config, config_path = load_config_from_context(
            context, missing_path_message="config_path is required in context"
        )
        log_config_source(context, listener.info, label="generate-reference-image")

        # ── Preview paths ─────────────────────────────────────────────
        preview_paths = config.get("rendered_preview_paths", [])
        if not preview_paths:
            raise ValueError(
                "rendered_preview_paths is required in generate_reference_image config. "
                "Ensure the render_preview step ran first."
            )

        # ── Image generation backend config ───────────────────────────
        image_gen_config: dict[str, Any] = config.get("image_gen", {})

        # ── Prompt ────────────────────────────────────────────────────
        # Accept prompt from config, or image_gen_prompt auto-generated
        # by identify_asset step, or identification for auto-generation
        prompt = config.get("prompt", "") or config.get("image_gen_prompt", "")
        if not prompt and config.get("identification"):
            # Will be auto-generated by GenerateReferenceImageTask
            listener.info("No explicit prompt — will auto-generate from identification")
        elif not prompt:
            raise ValueError(
                "prompt is required — describe the desired look for the "
                "reference image. Alternatively, run the identify_asset step "
                "first to auto-generate the prompt."
            )

        # ── Output directory ──────────────────────────────────────────
        output_dir = config.get("output_dir")
        if output_dir:
            output_dir = Path(output_dir)
            if not output_dir.is_absolute():
                output_dir = resolve_path_with_safe_diagnostics(
                    config_path.parent / output_dir,
                    label="generated-reference output directory",
                )
        else:
            output_dir = config_path.parent / "generated_refs"
        create_directory_with_safe_diagnostics(
            output_dir,
            label="generated-reference output directory",
        )

        # ── Number of images ──────────────────────────────────────────
        # Only pass through if explicitly > 1 in config.
        # Otherwise GenerateReferenceImageTask defaults to len(preview_paths).
        num_images_raw = config.get("num_images")
        # The executor may inject a default of 1 — ignore that
        num_images = (
            num_images_raw
            if isinstance(num_images_raw, int) and num_images_raw > 1
            else None
        )

        # ── Optional reference images ─────────────────────────────────
        reference_images: list[str] = config.get("reference_images", [])

        listener.info(f"  Preview images: {len(preview_paths)}")
        if reference_images:
            listener.info(f"  Reference images: {len(reference_images)}")
        listener.info(
            "  Backend: "
            f"{redact_sensitive_config(image_gen_config.get('backend', 'gemini'))}"
        )
        listener.info(
            "  Model: "
            f"{redact_sensitive_config(image_gen_config.get('model', '(default)'))}"
        )
        safe_prompt = str(redact_sensitive_config(prompt))
        listener.info(
            f"  Prompt: {safe_prompt[:80]}{'...' if len(safe_prompt) > 80 else ''}"
        )
        listener.info(f"  Output: {redact_sensitive_path(output_dir)}")
        num_display = num_images or "auto (match preview count)"
        listener.info(f"  Num images: {num_display}")

        context["rendered_preview_paths"] = preview_paths
        context["reference_images"] = reference_images
        context["image_gen_config"] = image_gen_config
        if prompt:
            context["image_gen_prompt"] = prompt
        context["output_dir"] = str(output_dir)
        if num_images is not None:
            context["num_images"] = num_images

        # Pass through identification from identify_asset step
        identification = config.get("identification")
        if identification:
            if not isinstance(identification, dict):
                raise TypeError(
                    f"identification must be a dict, "
                    f"got {type(identification).__name__}"
                )
            context["identification"] = identification

        # Pass through additional_prompt for composable instructions
        additional_prompt = config.get("additional_prompt", "")
        if additional_prompt:
            context["additional_prompt"] = additional_prompt

        return context
